(function(){
'use strict';
const ACCOUNT_API='https://dnqhikwqihfxvezqzqzn.supabase.co/functions/v1/nghi-son-account-api';
const ADMIN_API='https://dnqhikwqihfxvezqzqzn.supabase.co/functions/v1/nghi-son-admin-api';
const USERS_API='https://dnqhikwqihfxvezqzqzn.supabase.co/functions/v1/nghi-son-users-api';
let currentRoute=Api.isLoggedIn()?'home':'login';
function token(){return localStorage.getItem('auth_token')||''}
function esc(v){const d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML}
function roleLabel(r){return ({ADMIN:'Quản trị',MANAGER:'Quản lý',DRIVER:'Tài xế xe tải',OPERATOR:'Lái xe công trình'})[r]||r}
function toast(msg,type){const c=document.getElementById('toast-container');if(!c)return alert(msg);const x=document.createElement('div');x.className='toast '+(type||'')+' show';x.textContent=msg;c.appendChild(x);setTimeout(()=>x.remove(),2800)}
async function call(base,action,method='GET',body={}){let r;if(method==='GET'){const q=new URLSearchParams({...body,action,token:token()});r=await fetch(base+'?'+q.toString())}else{r=await fetch(base+'?action='+encodeURIComponent(action),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,token:token()})})}let j;try{j=await r.json()}catch(e){throw new Error('Không đọc được phản hồi máy chủ.')}if(!j.success)throw new Error(j.message||'Có lỗi xảy ra.');return j.data}
const accountGet=()=>call(ACCOUNT_API,'account');
const accountPost=(a,b)=>call(ACCOUNT_API,a,'POST',b);
const adminGet=(a,b={})=>call(ADMIN_API,a,'GET',b);
const adminPost=(a,b)=>call(ADMIN_API,a,'POST',b);
const usersGet=()=>call(USERS_API,'users');
const usersPost=(a,b)=>call(USERS_API,a,'POST',b);
async function tx(action,payload={}){payload.clientTransactionId=payload.clientTransactionId||crypto.randomUUID();if(navigator.onLine){try{return await Api.post(action,payload)}catch(e){if(e&&e.code&&e.code!=='PARSE_ERROR')throw new Error(e.message||'Không thực hiện được.')}}await OfflineQueue.enqueue(action,payload);await syncBanner();toast('Đã lưu tạm, sẽ đồng bộ khi có mạng.','warning');return {offline:true}}
function setActive(route){document.querySelectorAll('#bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===route))}
function setNav(show){document.getElementById('bottom-nav').classList.toggle('hidden',!show)}
function screen(html){document.getElementById('screen').innerHTML=html;window.scrollTo(0,0)}
function header(title,sub=''){return `<div class="app-header"><p class="greeting">${esc(sub)}</p><p class="user-name">${esc(title)}</p></div>`}
function pageHeader(title,back){return `<div class="page-header"><button class="back-btn" id="page-back">←</button><h2>${esc(title)}</h2></div>`}
function field(label,id,type='text',ph=''){return `<div class="field"><label>${esc(label)}</label><input id="${id}" type="${type}" ${type==='number'?'inputmode="decimal" step="0.1"':''} placeholder="${esc(ph)}"></div>`}
function selectField(label,id,items,fmt){return `<div class="field"><label>${esc(label)}</label><select class="select-field" id="${id}"><option value="">-- Chọn --</option>${items.map(x=>`<option value="${esc(x.id)}">${esc(fmt(x))}</option>`).join('')}</select></div>`}
function bigBtn(id,icon,label,danger=false){return `<button class="btn-big${danger?' danger-outline':''}" id="${id}"><span class="icon">${icon}</span><span>${esc(label)}</span></button>`}
function cardBtn(id,icon,label){return `<button id="${id}" style="width:100%;display:flex;align-items:center;gap:14px;padding:15px 16px;margin:9px 0;background:#fff;border:2px solid #15988f;border-radius:13px;color:#0f766e;font-weight:800;font-size:16px;text-align:left"><span style="font-size:24px">${icon}</span><span style="flex:1">${esc(label)}</span><span>›</span></button>`}
async function gps(){try{return await Gps.getCurrentPosition()}catch(e){return null}}
function route(r){currentRoute=r;render()}
window.navigate=route;
async function syncBanner(){const b=document.getElementById('sync-banner');if(!b)return;const n=await OfflineQueue.countPending();b.classList.toggle('show',n>0);const t=b.querySelector('.sync-text');if(t)t.textContent='Có '+n+' giao dịch chờ đồng bộ.'}
function network(){const e=document.getElementById('network-status');if(e){e.textContent=navigator.onLine?'🟢 Online':'🟠 Offline';e.classList.toggle('offline',!navigator.onLine)}syncBanner()}
window.addEventListener('online',network);window.addEventListener('offline',network);

document.addEventListener('DOMContentLoaded',()=>{
 document.querySelectorAll('#bottom-nav button').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();route(b.dataset.route)}));
 const sb=document.getElementById('sync-now-btn');if(sb)sb.onclick=async()=>{if(!navigator.onLine)return toast('Chưa có mạng.','warning');const r=await OfflineQueue.syncAll();await syncBanner();toast(`Đồng bộ ${r.success||0} thành công, ${r.failed||0} lỗi.`,r.failed?'warning':'success')};
 network();render();
});

async function render(){
 if(!Api.isLoggedIn()&&currentRoute!=='login')currentRoute='login';
 setNav(currentRoute!=='login');setActive(currentRoute);
 try{
  if(currentRoute==='login')return login();
  if(currentRoute==='home')return home();
  if(currentRoute==='history')return history();
  if(currentRoute==='operations-v2')return operations();
  if(currentRoute==='account')return account();
  return home();
 }catch(e){screen(`<div class="screen"><div class="form-error show" style="margin:20px">${esc(e.message||e)}</div></div>`)}
}

function login(){setNav(false);screen(`<div class="screen login-screen"><div class="login-logo">🚜</div><h1 class="login-title">Nhật Ký Vận Hành Nghi Sơn</h1><p class="login-subtitle">Đăng nhập để làm việc</p><div class="form-error" id="login-error"></div>${field('Số điện thoại','login-phone','tel','09xxxxxxxx')}${field('Mật khẩu','login-password','password','Nhập mật khẩu')}<button class="btn-primary" id="login-btn">ĐĂNG NHẬP</button></div>`);document.getElementById('login-btn').onclick=async()=>{const b=document.getElementById('login-btn'),err=document.getElementById('login-error');err.classList.remove('show');try{b.disabled=true;b.textContent='Đang đăng nhập...';await Api.login(document.getElementById('login-phone').value,document.getElementById('login-password').value);currentRoute='home';setNav(true);render()}catch(e){err.textContent=e.message||'Không đăng nhập được.';err.classList.add('show')}finally{b.disabled=false;b.textContent='ĐĂNG NHẬP'}}}

async function home(){const u=Api.getCurrentUser();if(!u)return route('login');if(u.ROLE==='ADMIN')return adminHome(u);if(u.ROLE==='MANAGER')return managerHome(u);if(u.ROLE==='DRIVER')return driverHome(u);if(u.ROLE==='OPERATOR')return operatorHome(u);screen(`<div class="screen">${header(u.FULL_NAME,'Trang chủ')}<div class="empty-state">Vai trò chưa được cấu hình.</div></div>`)}
async function driverHome(u){const [acc,h]=await Promise.all([accountGet(),Api.get('home',{})]);const sel=acc.selectedAsset;let body='';if(!sel){body=`<div class="account-card"><p class="name">Chưa chọn xe tải</p><p>Vào Tài khoản để chọn xe trước khi bắt đầu chuyến.</p></div>${bigBtn('go-select','🚚','CHỌN XE TẢI')}`;}else if(h.currentTrip){const c=h.currentTrip;body=`<div class="account-card"><p class="name">🚚 ${esc(sel.plate_number||sel.code)}</p><div class="detail-row"><span>Tuyến</span><span>${esc(c.ROUTE_NAME||'—')}</span></div><div class="detail-row"><span>Hành trình</span><span>${esc((c.ORIGIN||'')+' → '+(c.DESTINATION||''))}</span></div><div class="detail-row"><span>Trạng thái</span><span>Đang chạy</span></div></div>${bigBtn('finish-trip','⏹','KẾT THÚC CHUYẾN')}`;}else{body=`<div class="account-card"><div class="detail-row"><span>Xe đang chọn</span><span><b>${esc(sel.plate_number||sel.code)}</b></span></div>${selectField('Tuyến','route-select',h.routes||[],x=>x.name+' · '+x.origin+' → '+x.destination)}</div>${bigBtn('start-trip','▶','BẮT ĐẦU CHUYẾN')}`;}screen(`<div class="screen">${header(u.FULL_NAME,'Tài xế xe tải')}<div class="action-list">${body}</div></div>`);const gs=document.getElementById('go-select');if(gs)gs.onclick=()=>vehicleSelect();const st=document.getElementById('start-trip');if(st)st.onclick=async()=>{const rid=document.getElementById('route-select').value;if(!rid)return toast('Vui lòng chọn tuyến.','error');try{st.disabled=true;const g=await gps();await tx('trip/start',{vehicleId:sel.id,routeId:rid,lat:g?.latitude,lng:g?.longitude});toast('Đã bắt đầu chuyến.','success');home()}catch(e){toast(e.message,'error');st.disabled=false}};const ft=document.getElementById('finish-trip');if(ft)ft.onclick=async()=>{try{ft.disabled=true;const g=await gps();await tx('trip/complete',{lat:g?.latitude,lng:g?.longitude});toast('Đã kết thúc chuyến.','success');home()}catch(e){toast(e.message,'error');ft.disabled=false}}}
async function operatorHome(u){const [acc,h]=await Promise.all([accountGet(),Api.get('home',{})]);const sel=acc.selectedAsset;let body='';if(!sel){body=`<div class="account-card"><p class="name">Chưa chọn xe công trình</p><p>Vào Tài khoản để chọn xe trước khi bắt đầu.</p></div>${bigBtn('go-select','🚜','CHỌN XE CÔNG TRÌNH')}`;}else if(h.currentShift){const c=h.currentShift;body=`<div class="account-card"><p class="name">🚜 ${esc(sel.name||sel.code)}</p><div class="detail-row"><span>Công việc</span><span>${esc(c.WORK_TYPE_NAME||'—')}</span></div><div class="detail-row"><span>Bắt đầu</span><span>${esc(new Date(c.START_AT).toLocaleString('vi-VN'))}</span></div></div>${field('Giờ máy cuối','end-meter','number')}${bigBtn('finish-shift','⏹','KẾT THÚC')}`;}else{body=`<div class="account-card"><div class="detail-row"><span>Xe đang chọn</span><span><b>${esc(sel.name||sel.code)}</b></span></div>${selectField('Công việc','work-select',h.workTypes||[],x=>x.name)}${field('Giờ máy đầu','start-meter','number')}</div>${bigBtn('start-shift','▶','BẮT ĐẦU')}`;}screen(`<div class="screen">${header(u.FULL_NAME,'Lái xe công trình')}<div class="action-list">${body}</div></div>`);const gs=document.getElementById('go-select');if(gs)gs.onclick=()=>vehicleSelect();const st=document.getElementById('start-shift');if(st)st.onclick=async()=>{const wid=document.getElementById('work-select').value;if(!wid)return toast('Vui lòng chọn công việc.','error');try{st.disabled=true;const g=await gps();await tx('shift/start',{machineId:sel.id,workTypeId:wid,startHourMeter:Number(document.getElementById('start-meter').value||0)||null,lat:g?.latitude,lng:g?.longitude});toast('Đã bắt đầu.','success');home()}catch(e){toast(e.message,'error');st.disabled=false}};const fs=document.getElementById('finish-shift');if(fs)fs.onclick=async()=>{try{fs.disabled=true;const g=await gps();await tx('shift/end',{endHourMeter:Number(document.getElementById('end-meter').value||0)||null,lat:g?.latitude,lng:g?.longitude});toast('Đã kết thúc.','success');home()}catch(e){toast(e.message,'error');fs.disabled=false}}}
async function adminHome(u){const d=await adminGet('dashboard');const s=d.summary||{};screen(`<div class="screen">${header(u.FULL_NAME,'Báo cáo tổng quan')}<div class="stat-grid"><div class="stat-card"><p class="stat-value">${s.totalVehicles||0}</p><p class="stat-label">Xe tải</p></div><div class="stat-card"><p class="stat-value">${s.totalMachines||0}</p><p class="stat-label">Xe công trình</p></div><div class="stat-card"><p class="stat-value">${s.activeTripCount||0}</p><p class="stat-label">Chuyến đang chạy</p></div><div class="stat-card"><p class="stat-value">${s.activeCount||0}</p><p class="stat-label">Ca đang chạy</p></div><div class="stat-card"><p class="stat-value">${Number(s.todayFuelTotal||0).toLocaleString('vi-VN')}</p><p class="stat-label">Dầu hôm nay (L)</p></div><div class="stat-card"><p class="stat-value">${s.openIssueCount||0}</p><p class="stat-label">Sự cố chưa xử lý</p></div></div></div>`)}
async function managerHome(u){const now=new Date(),from=new Date(now.getFullYear(),now.getMonth(),1).toISOString().slice(0,10),to=now.toISOString().slice(0,10),r=await Api.get('report/summary',{from,to});screen(`<div class="screen">${header(u.FULL_NAME,'Tổng quan tháng')}<div class="stat-grid"><div class="stat-card"><p class="stat-value">${r.trips||0}</p><p class="stat-label">Chuyến</p></div><div class="stat-card"><p class="stat-value">${r.completedTrips||0}</p><p class="stat-label">Hoàn thành</p></div><div class="stat-card"><p class="stat-value">${Number(r.fuelLiters||0).toLocaleString('vi-VN')}</p><p class="stat-label">Lít dầu</p></div><div class="stat-card"><p class="stat-value">${r.openIssues||0}</p><p class="stat-label">Sự cố mở</p></div></div></div>`)}

async function operations(){const u=Api.getCurrentUser();if(!u)return route('login');if(!['DRIVER','OPERATOR'].includes(u.ROLE)){screen(`<div class="screen">${header('Vận hành','')}<div class="empty-state">Không có nghiệp vụ vận hành cho vai trò này.</div></div>`);return}const [acc,h]=await Promise.all([accountGet(),Api.get('home',{})]);let stop='';if(u.ROLE==='DRIVER'&&h.currentTrip)stop=bigBtn('op-stop','⛔','DỪNG XE DO SỰ CỐ',true);screen(`<div class="screen">${header('Vận hành','Các nghiệp vụ phát sinh')}<div class="action-list">${bigBtn('op-fuel','⛽','ĐỔ DẦU')}${bigBtn('op-issue','🔧','GHI NHẬN SỰ CỐ')}${stop}</div></div>`);document.getElementById('op-fuel').onclick=()=>fuelForm(acc);document.getElementById('op-issue').onclick=()=>issueForm(acc);const b=document.getElementById('op-stop');if(b)b.onclick=()=>stopForm(acc)}
function fuelForm(acc){currentRoute='operations-v2';screen(`<div class="screen">${pageHeader('Đổ dầu')}<div class="page-body"><div class="account-card"><div class="detail-row"><span>Xe/máy</span><span>${esc(acc.selectedAsset?.plate_number||acc.selectedAsset?.name||acc.selectedAsset?.code||'Chưa chọn')}</span></div></div>${field('Số lít *','fuel-qty','number')}${field('Công tơ mét / giờ máy','fuel-meter','number')}${field('Ghi chú','fuel-note')}${bigBtn('fuel-save','💾','GHI NHẬN')}</div></div>`);document.getElementById('page-back').onclick=()=>operations();document.getElementById('fuel-save').onclick=async()=>{const q=Number(document.getElementById('fuel-qty').value||0);if(q<=0)return toast('Số lít phải lớn hơn 0.','error');if(!acc.selectedAsset)return toast('Vui lòng chọn xe trước.','error');try{await tx('fuel',{quantity:q,hourMeter:Number(document.getElementById('fuel-meter').value||0)||null,note:document.getElementById('fuel-note').value,[Api.getCurrentUser().ROLE==='DRIVER'?'vehicleId':'machineId']:acc.selectedAsset.id});toast('Đã ghi nhận đổ dầu.','success');operations()}catch(e){toast(e.message,'error')}}}
function issueForm(acc){screen(`<div class="screen">${pageHeader('Ghi nhận sự cố')}<div class="page-body">${field('Loại sự cố','issue-type','text','Động cơ, lốp, thủy lực...')}${field('Mô tả *','issue-desc')}<div class="field"><label>Mức độ</label><select class="select-field" id="issue-sev"><option value="LOW">Vẫn hoạt động</option><option value="MEDIUM">Hoạt động hạn chế</option><option value="HIGH">Phải dừng xe/máy</option></select></div>${bigBtn('issue-save','🔧','GHI NHẬN',true)}</div></div>`);document.getElementById('page-back').onclick=()=>operations();document.getElementById('issue-save').onclick=async()=>{const desc=document.getElementById('issue-desc').value.trim();if(!desc)return toast('Vui lòng nhập mô tả.','error');if(!acc.selectedAsset)return toast('Vui lòng chọn xe trước.','error');try{await tx('issue',{issueType:document.getElementById('issue-type').value,severity:document.getElementById('issue-sev').value,description:desc,[Api.getCurrentUser().ROLE==='DRIVER'?'vehicleId':'machineId']:acc.selectedAsset.id});toast('Đã ghi nhận sự cố.','success');operations()}catch(e){toast(e.message,'error')}}}
function stopForm(acc){screen(`<div class="screen">${pageHeader('Dừng xe do sự cố')}<div class="page-body"><p>Hệ thống sẽ dừng chuyến và đồng thời ghi nhận sự cố.</p>${field('Loại sự cố','stop-type','text','Lốp, phanh, động cơ...')}${field('Mô tả *','stop-desc')}${bigBtn('stop-save','⛔','DỪNG XE VÀ GHI NHẬN',true)}</div></div>`);document.getElementById('page-back').onclick=()=>operations();document.getElementById('stop-save').onclick=async()=>{const desc=document.getElementById('stop-desc').value.trim();if(!desc)return toast('Vui lòng nhập mô tả.','error');try{const g=await gps();await tx('trip/pause',{reason:'INCIDENT',note:desc,lat:g?.latitude,lng:g?.longitude});await tx('issue',{vehicleId:acc.selectedAsset?.id,issueType:document.getElementById('stop-type').value,severity:'HIGH',description:desc,lat:g?.latitude,lng:g?.longitude});toast('Đã dừng xe và ghi nhận sự cố.','success');operations()}catch(e){toast(e.message,'error')}}}

async function history(){const rows=await Api.get('history',{limit:100});const html=(rows||[]).map(x=>`<div class="account-card" style="margin-bottom:10px"><p class="name">${esc(x.title||x.KIND||'Nhật ký')}</p><div>${esc(x.subtitle||'')}</div><div style="font-size:13px;color:#6b7280;margin-top:6px">${esc(new Date(x.time||x.CREATED_AT).toLocaleString('vi-VN'))} · ${esc(x.status||'')}</div></div>`).join('')||'<div class="empty-state">Chưa có nhật ký.</div>';screen(`<div class="screen">${header('Nhật ký','Hoạt động gần đây')}<div style="padding:16px">${html}</div></div>`)}

async function account(){const u=Api.getCurrentUser();const acc=await accountGet();let assetPart='';if(['DRIVER','OPERATOR'].includes(u.ROLE)){assetPart=`<div class="account-card"><p class="name">Xe đang chọn</p><div class="detail-row"><span>Phương tiện</span><span>${esc(acc.selectedAsset?.plate_number||acc.selectedAsset?.name||'Chưa chọn')}</span></div>${bigBtn('choose-vehicle','🔄',acc.selectedAsset?'CHỌN/THAY XE':'CHỌN XE')}</div>`}let adminPart='';if(u.ROLE==='ADMIN'){adminPart=`<div style="padding:0 16px 12px"><h3 style="margin:8px 0 10px">Quản trị hệ thống</h3>${cardBtn('adm-users','👥','Người dùng')}${cardBtn('adm-vehicles','🚚','Phương tiện')}${cardBtn('adm-trips','🧾','Chuyến xe')}${cardBtn('adm-routes','🛣','Tuyến')}${cardBtn('adm-work','🔧','Loại công việc')}</div>`}screen(`<div class="screen">${header(u.FULL_NAME,'Tài khoản')}<div class="account-card"><p class="name">${esc(u.FULL_NAME)}</p><span class="role-badge">${esc(roleLabel(u.ROLE))}</span><div class="detail-row"><span>Số điện thoại</span><span>${esc(u.PHONE||'')}</span></div></div>${assetPart}<div style="padding:0 16px">${bigBtn('change-pass','🔐','ĐỔI MẬT KHẨU')}<div id="password-form" style="display:none" class="account-card">${field('Mật khẩu cũ','old-pass','password')}${field('Mật khẩu mới','new-pass','password')}${field('Xác nhận mật khẩu mới','confirm-pass','password')}<button class="btn-primary" id="confirm-pass-btn">XÁC NHẬN THAY ĐỔI</button></div></div>${adminPart}<button class="btn-logout" id="logout-btn">ĐĂNG XUẤT</button></div>`);const cv=document.getElementById('choose-vehicle');if(cv)cv.onclick=vehicleSelect;document.getElementById('change-pass').onclick=()=>{const f=document.getElementById('password-form');f.style.display=f.style.display==='none'?'block':'none'};document.getElementById('confirm-pass-btn').onclick=async()=>{const oldp=document.getElementById('old-pass').value,np=document.getElementById('new-pass').value,cp=document.getElementById('confirm-pass').value;if(np!==cp)return toast('Xác nhận mật khẩu mới không khớp.','error');try{await accountPost('change-password',{oldPassword:oldp,newPassword:np});toast('Đã đổi mật khẩu.','success');document.getElementById('password-form').style.display='none'}catch(e){toast(e.message,'error')}};document.getElementById('logout-btn').onclick=async()=>{await Api.logout();currentRoute='login';render()};if(u.ROLE==='ADMIN'){document.getElementById('adm-users').onclick=adminUsers;document.getElementById('adm-vehicles').onclick=()=>adminList('vehicles');document.getElementById('adm-trips').onclick=()=>adminList('trips');document.getElementById('adm-routes').onclick=()=>adminList('routes');document.getElementById('adm-work').onclick=()=>adminList('work-types')}}
async function vehicleSelect(){const acc=await accountGet();const assets=acc.assets||[];const rows=assets.map(a=>`<button class="vehicle-choice" data-id="${a.id}" style="width:100%;padding:14px;margin:8px 0;text-align:left;background:white;border:2px solid ${acc.selectedAsset?.id===a.id?'#15988f':'#e5e7eb'};border-radius:12px"><b>${esc(a.plate_number||a.name||a.code)}</b><div style="font-size:13px;color:#6b7280">${esc(a.name||a.code)}</div></button>`).join('')||'<div class="empty-state">Không có xe phù hợp vai trò.</div>';screen(`<div class="screen">${pageHeader('Chọn/Thay xe')}<div class="page-body">${rows}</div></div>`);document.getElementById('page-back').onclick=()=>account();document.querySelectorAll('.vehicle-choice').forEach(b=>b.onclick=async()=>{try{await accountPost('select-vehicle',{assetId:b.dataset.id});toast('Đã chọn xe.','success');account()}catch(e){toast(e.message,'error')}})}

async function adminUsers(){const users=await usersGet();const rows=users.map(x=>{const p=x.profiles||{};return `<div class="account-card" style="margin-bottom:10px"><p class="name">${esc(p.full_name||'Chưa đặt tên')}</p><div>${esc(p.phone||'')}</div><div style="font-size:13px;color:#6b7280;margin:5px 0">${esc(roleLabel(x.role_code))} · ${x.is_active?'Đang hoạt động':'Đã khóa'}</div><div class="field"><label>Vai trò</label><select class="select-field user-role" data-id="${p.id}"><option value="DRIVER" ${x.role_code==='DRIVER'?'selected':''}>Tài xế xe tải</option><option value="OPERATOR" ${x.role_code==='OPERATOR'?'selected':''}>Lái xe công trình</option><option value="MANAGER" ${x.role_code==='MANAGER'?'selected':''}>Quản lý</option><option value="ADMIN" ${x.role_code==='ADMIN'?'selected':''}>Quản trị</option></select></div><button class="btn-primary save-role" data-id="${p.id}">LƯU VAI TRÒ</button><button class="btn-primary reset-pass" data-id="${p.id}" style="margin-top:8px;background:#475569">ĐẶT LẠI MẬT KHẨU</button><button class="btn-logout toggle-user" data-id="${p.id}" data-active="${!x.is_active}" style="margin-top:8px">${x.is_active?'KHÓA TÀI KHOẢN':'MỞ TÀI KHOẢN'}</button></div>`}).join('');screen(`<div class="screen">${pageHeader('Người dùng')}<div class="page-body"><button class="btn-primary" id="new-user">+ TẠO MỚI</button><div style="margin-top:14px">${rows||'<div>Chưa có người dùng.</div>'}</div></div></div>`);document.getElementById('page-back').onclick=()=>account();document.getElementById('new-user').onclick=adminCreateUser;document.querySelectorAll('.save-role').forEach(b=>b.onclick=async()=>{const s=document.querySelector(`.user-role[data-id="${b.dataset.id}"]`);try{await usersPost('user/update-role',{profileId:b.dataset.id,roleCode:s.value});toast('Đã đổi vai trò. Người dùng cần đăng nhập lại.','success');adminUsers()}catch(e){toast(e.message,'error')}});document.querySelectorAll('.reset-pass').forEach(b=>b.onclick=async()=>{const p=prompt('Nhập mật khẩu mới (từ 4 ký tự):');if(!p)return;try{await usersPost('user/reset-password',{profileId:b.dataset.id,newPassword:p});toast('Đã đặt lại mật khẩu.','success')}catch(e){toast(e.message,'error')}});document.querySelectorAll('.toggle-user').forEach(b=>b.onclick=async()=>{try{await usersPost('user/toggle',{profileId:b.dataset.id,isActive:b.dataset.active==='true'});adminUsers()}catch(e){toast(e.message,'error')}})}
function adminCreateUser(){screen(`<div class="screen">${pageHeader('Tạo người dùng')}<div class="page-body">${field('Họ tên *','u-name')}${field('Số điện thoại *','u-phone','tel','09xxxxxxxx')}<div class="field"><label>Vai trò</label><select class="select-field" id="u-role"><option value="DRIVER">Tài xế xe tải</option><option value="OPERATOR">Lái xe công trình</option><option value="MANAGER">Quản lý</option><option value="ADMIN">Quản trị</option></select></div>${field('Mật khẩu ban đầu *','u-pass','password')}<button class="btn-primary" id="u-save">TẠO TÀI KHOẢN</button></div></div>`);document.getElementById('page-back').onclick=adminUsers;document.getElementById('u-save').onclick=async()=>{try{await usersPost('user/create',{fullName:document.getElementById('u-name').value,phone:document.getElementById('u-phone').value,roleCode:document.getElementById('u-role').value,password:document.getElementById('u-pass').value});toast('Đã tạo tài khoản.','success');adminUsers()}catch(e){toast(e.message,'error')}}}
async function adminList(kind){let data,title,createLabel;if(kind==='vehicles'){data=await adminGet('vehicles');title='Phương tiện';createLabel='+ TẠO PHƯƠNG TIỆN'}if(kind==='trips'){data=await adminGet('trips');title='Chuyến xe';createLabel='+ TẠO CHUYẾN'}if(kind==='routes'){data=await adminGet('routes');title='Tuyến';createLabel='+ TẠO TUYẾN'}if(kind==='work-types'){data=await adminGet('work-types');title='Loại công việc';createLabel='+ TẠO CÔNG VIỆC'}let rows='';if(kind==='vehicles')rows=(data||[]).map(x=>`<div class="account-card"><p class="name">${esc(x.plate_number||x.name||x.code)}</p><div>${esc(x.asset_type==='TRUCK'?'Xe tải':'Xe công trình')} · ${esc(x.status)}</div></div>`).join('');if(kind==='trips')rows=(data||[]).map(x=>`<div class="account-card"><p class="name">${esc(x.assets?.plate_number||x.assets?.code||'Chuyến')}</p><div>${esc(x.routes?.name||((x.origin||'')+' → '+(x.destination||'')))}</div><small>${esc(x.trip_date)} · ${esc(x.status)}</small></div>`).join('');if(kind==='routes')rows=(data||[]).map(x=>`<div class="account-card"><p class="name">${esc(x.name)}</p><div>${esc(x.origin)} → ${esc(x.destination)}</div></div>`).join('');if(kind==='work-types')rows=(data||[]).map(x=>`<div class="account-card"><p class="name">${esc(x.name)}</p><div>${esc(x.description||'')}</div></div>`).join('');screen(`<div class="screen">${pageHeader(title)}<div class="page-body"><button class="btn-primary" id="admin-create">${createLabel}</button><div style="margin-top:14px">${rows||'<div>Chưa có dữ liệu.</div>'}</div></div></div>`);document.getElementById('page-back').onclick=()=>account();document.getElementById('admin-create').onclick=()=>adminCreate(kind)}
async function adminCreate(kind){if(kind==='vehicles'){screen(`<div class="screen">${pageHeader('Tạo phương tiện')}<div class="page-body">${field('Biển số *','v-plate')}<div class="field"><label>Loại</label><select class="select-field" id="v-type"><option value="TRUCK">Xe tải</option><option value="MACHINE">Xe công trình</option></select></div>${field('Tên hiển thị','v-name')}${field('Hãng','v-brand')}${field('Model','v-model')}<button class="btn-primary" id="v-save">LƯU</button></div></div>`);document.getElementById('page-back').onclick=()=>adminList(kind);document.getElementById('v-save').onclick=async()=>{try{await adminPost('vehicle/add',{plateNumber:document.getElementById('v-plate').value,assetType:document.getElementById('v-type').value,name:document.getElementById('v-name').value,brand:document.getElementById('v-brand').value,model:document.getElementById('v-model').value});toast('Đã tạo phương tiện.','success');adminList(kind)}catch(e){toast(e.message,'error')}};return}
if(kind==='routes'){screen(`<div class="screen">${pageHeader('Tạo tuyến')}<div class="page-body">${field('Tên tuyến *','r-name')}${field('Điểm đi *','r-origin')}${field('Điểm đến *','r-dest')}${field('Km chuẩn','r-km','number')}${field('Loại hàng mặc định','r-cargo')}<button class="btn-primary" id="r-save">LƯU</button></div></div>`);document.getElementById('page-back').onclick=()=>adminList(kind);document.getElementById('r-save').onclick=async()=>{try{await adminPost('route/add',{name:document.getElementById('r-name').value,origin:document.getElementById('r-origin').value,destination:document.getElementById('r-dest').value,distanceKm:Number(document.getElementById('r-km').value||0)||null,defaultCargoType:document.getElementById('r-cargo').value});toast('Đã tạo tuyến.','success');adminList(kind)}catch(e){toast(e.message,'error')}};return}
if(kind==='work-types'){screen(`<div class="screen">${pageHeader('Tạo loại công việc')}<div class="page-body">${field('Tên công việc *','w-name')}${field('Mô tả','w-desc')}<button class="btn-primary" id="w-save">LƯU</button></div></div>`);document.getElementById('page-back').onclick=()=>adminList(kind);document.getElementById('w-save').onclick=async()=>{try{await adminPost('work-type/add',{name:document.getElementById('w-name').value,description:document.getElementById('w-desc').value});toast('Đã tạo công việc.','success');adminList(kind)}catch(e){toast(e.message,'error')}};return}
if(kind==='trips'){const [vs,rs,us]=await Promise.all([adminGet('vehicles'),adminGet('routes'),usersGet()]);const drivers=(us||[]).filter(x=>x.role_code==='DRIVER'&&x.is_active).map(x=>x.profiles).filter(Boolean);screen(`<div class="screen">${pageHeader('Tạo chuyến')}<div class="page-body">${selectField('Xe tải *','t-vehicle',(vs||[]).filter(x=>x.asset_type==='TRUCK'),x=>(x.plate_number||x.code))}${selectField('Tuyến','t-route',rs||[],x=>x.name)}${selectField('Tài xế','t-driver',drivers,x=>x.full_name+' - '+x.phone)}${field('Ngày','t-date','date')}${field('Loại hàng','t-cargo')}<button class="btn-primary" id="t-save">TẠO CHUYẾN</button></div></div>`);document.getElementById('t-date').value=new Date().toISOString().slice(0,10);document.getElementById('page-back').onclick=()=>adminList(kind);document.getElementById('t-save').onclick=async()=>{try{await adminPost('trip/create',{vehicleId:document.getElementById('t-vehicle').value,routeId:document.getElementById('t-route').value||null,driverProfileId:document.getElementById('t-driver').value||null,tripDate:document.getElementById('t-date').value,cargoType:document.getElementById('t-cargo').value,clientTransactionId:crypto.randomUUID()});toast('Đã tạo chuyến.','success');adminList(kind)}catch(e){toast(e.message,'error')}}}}
})();