// Nhật ký UI v2: nút Chi tiết luôn hiển thị + KPI nhanh Tổng chuyến / Sự kiện (Đổ dầu + Sự cố).
(function(){
'use strict';
if(window.__NS_HISTORY_UI_V2)return;window.__NS_HISTORY_UI_V2=true;
const API='https://dnqhikwqihfxvezqzqzn.supabase.co/functions/v1/nghi-son-history-api';
let scheduled=false,kpiBusy=false,lastRange='';
function token(){return localStorage.getItem('auth_token')||''}
function esc(v){const d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML}
function fmt(v){if(!v)return '—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function num(v,s=''){if(v==null||v==='')return '—';return Number(v).toLocaleString('vi-VN')+(s?' '+s:'')}
function status(v){return({IN_PROGRESS:'Đang chạy',COMPLETED:'Hoàn thành',OPEN:'Đang hoạt động',REPORTED:'Tạo mới',CANCELLED:'Đã hủy'})[v]||v||'—'}
function severity(v){return({LOW:'Vẫn hoạt động',MEDIUM:'Hoạt động hạn chế',HIGH:'Phải dừng'})[v]||v||'—'}
function kindLabel(k){return({trip:'Chuyến',fuel:'Đổ dầu',issue:'Sự cố',repair:'Sửa chữa',shift:'Ca máy'})[k]||k}
function get(params){const q=new URLSearchParams({...params,token:token()});return fetch(API+'?'+q.toString()).then(r=>r.json()).then(j=>{if(!j.success)throw new Error(j.message||'Không tải được dữ liệu.');return j.data})}
function css(){if(document.getElementById('ns-history-ui-v2-css'))return;const s=document.createElement('style');s.id='ns-history-ui-v2-css';s.textContent=`
#hist-body .ns-h-card{position:relative!important;padding-top:15px!important;padding-right:16px!important}
#hist-body .ns-h-card>div:nth-child(2){min-width:0;padding-right:64px!important}
#hist-body .ns-h-card h4{padding-right:0!important;white-space:normal!important}
#hist-body .ns-h-card:after{display:none!important;content:none!important}
.ns-history-detail-btn{position:absolute;right:14px;top:13px;border:0;background:transparent;color:#087173;font-size:13px;font-weight:900;line-height:1;padding:5px 2px;z-index:8;cursor:pointer}
.ns-history-detail-btn:active{opacity:.6}
.ns-history-kpis{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:0 0 14px}
.ns-history-kpi{background:#fff;border:1px solid #dfe7ea;border-radius:14px;padding:12px 13px;min-height:78px;display:flex;flex-direction:column;justify-content:center}
.ns-history-kpi b{font-size:23px;line-height:1.05;color:#087173;letter-spacing:-.3px}.ns-history-kpi span{margin-top:6px;font-size:12px;font-weight:750;color:#667085}
.ns-history-kpi:first-child b{color:#2563eb}
.ns-h-modal{position:fixed;inset:0;z-index:10020;background:rgba(15,23,42,.42);display:flex;align-items:flex-end;justify-content:center}
.ns-h-sheet{width:min(100%,560px);max-height:88vh;overflow:auto;background:#f8fafc;border-radius:24px 24px 0 0;padding:18px 16px calc(22px + env(safe-area-inset-bottom));box-shadow:0 -12px 30px rgba(15,23,42,.18)}
.ns-h-sheet-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:10px}.ns-h-sheet-head h3{margin:0;font-size:20px}.ns-h-sheet-close{border:0;background:#e2e8f0;width:38px;height:38px;border-radius:50%;font-size:24px}
.ns-h-sheet-card{background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:14px}.ns-h-sheet-row{display:grid;grid-template-columns:124px minmax(0,1fr);gap:12px;padding:9px 0;border-bottom:1px solid #eef2f7}.ns-h-sheet-row:last-child{border-bottom:0}.ns-h-sheet-row span:first-child{color:#64748b;font-size:13px}.ns-h-sheet-row b,.ns-h-sheet-row span:last-child{text-align:right;word-break:break-word}.ns-h-sheet-map{display:inline-block;margin-top:4px;color:#087173;font-weight:850;text-decoration:none}
@media(max-width:390px){.ns-h-sheet-row{grid-template-columns:108px minmax(0,1fr)}.ns-history-kpi{padding:11px 10px}.ns-history-kpi b{font-size:21px}}
`;document.head.appendChild(s)}
function row(k,v,html=false){return `<div class="ns-h-sheet-row"><span>${esc(k)}</span>${html?`<span>${v}</span>`:`<b>${esc(v==null||v===''?'—':v)}</b>`}</div>`}
function map(loc){if(!loc||loc.latitude==null||loc.longitude==null)return 'Không có tọa độ';const lat=Number(loc.latitude),lng=Number(loc.longitude);return `${esc(lat.toFixed(6)+', '+lng.toFixed(6))}<br><a class="ns-h-sheet-map" target="_blank" rel="noopener" href="https://www.google.com/maps?q=${lat},${lng}">Mở trên bản đồ</a>`}
function detailRows(d){let h='';if(d.type==='trip'){h+=row('Biển số xe',d.asset)+row('Tuyến',d.route||`${d.origin||''} → ${d.destination||''}`)+row('Bắt đầu',fmt(d.startedAt))+row('Tọa độ bắt đầu',map(d.startLocation),true)+row('Kết thúc',fmt(d.endedAt))+row('Tọa độ kết thúc',map(d.endLocation),true)+row('Trạng thái',status(d.status));if(d.cargoType)h+=row('Hàng hóa',d.cargoType);if(d.quantity!=null)h+=row('Khối lượng',num(d.quantity,d.quantityUnit));if(d.distanceKm!=null)h+=row('Quãng đường',num(d.distanceKm,'km'));if(d.note)h+=row('Ghi chú',d.note)}else if(d.type==='fuel'){h+=row('Phương tiện',d.asset)+row('Thời gian',fmt(d.time))+row('Số dầu đổ',num(d.quantityLiters,'lít'))+row('Km / giờ máy',num(d.meterValue))+row('Tọa độ',map(d.location),true)+row('Trạng thái GPS',d.location?.gpsStatus||'—');if(d.note)h+=row('Ghi chú',d.note)}else if(d.type==='issue'||d.type==='repair'){h+=row('Phương tiện',d.asset)+row('Thời gian',fmt(d.time));if(d.issueType)h+=row('Loại sự cố',d.issueType);h+=row('Nội dung',d.description||'—');if(d.type==='issue')h+=row('Mức độ',severity(d.severity));h+=row('Trạng thái',status(d.status))+row('Tọa độ',map(d.location),true);if(d.vendor)h+=row('Đơn vị sửa',d.vendor);if(d.completedAt)h+=row('Hoàn thành',fmt(d.completedAt));if(d.actualAmount!=null)h+=row('Chi phí',num(d.actualAmount,'đ'));if(d.note)h+=row('Ghi chú',d.note)}else if(d.type==='shift'){h+=row('Xe / máy',d.asset)+row('Công việc',d.workType)+row('Bắt đầu',fmt(d.startedAt))+row('Tọa độ bắt đầu',map(d.startLocation),true)+row('Kết thúc',fmt(d.endedAt))+row('Tọa độ kết thúc',map(d.endLocation),true)+row('Giờ máy đầu',num(d.startMeter))+row('Giờ máy cuối',num(d.endMeter))+row('Số giờ',num(d.workingHours,'giờ'))+row('Trạng thái',status(d.status))}return h}
function modal(){let m=document.getElementById('ns-history-modal');if(m)m.remove();m=document.createElement('div');m.id='ns-history-modal';m.className='ns-h-modal';m.innerHTML='<div class="ns-h-sheet"><div class="ns-h-sheet-head"><h3 id="ns-history-modal-title">Chi tiết</h3><button type="button" class="ns-h-sheet-close" aria-label="Đóng">×</button></div><div id="ns-history-modal-body" class="ns-h-sheet-card">Đang tải...</div></div>';document.body.appendChild(m);m.querySelector('.ns-h-sheet-close').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};return m}
async function openDetail(type,id){if(!id||!type)return;const m=modal(),title=m.querySelector('#ns-history-modal-title'),body=m.querySelector('#ns-history-modal-body');title.textContent='Chi tiết '+kindLabel(type);try{const d=await get({action:'detail',type,id});body.innerHTML=detailRows(d)}catch(e){body.textContent=e.message||String(e)}}
function addButtons(){document.querySelectorAll('#hist-body .ns-h-card').forEach(card=>{let b=card.querySelector(':scope > .ns-history-detail-btn');if(!b){b=document.createElement('button');b.type='button';b.className='ns-history-detail-btn';b.textContent='Chi tiết';card.appendChild(b)}b.dataset.type=card.dataset.hType||'';b.dataset.id=card.dataset.hId||'';b.onclick=e=>{e.preventDefault();e.stopPropagation();openDetail(b.dataset.type,b.dataset.id)}})}
async function refreshKpis(force=false){const body=document.getElementById('hist-body'),range=document.getElementById('hist-range');if(!body||!range||kpiBusy)return;const rv=range.value||'today';if(!force&&lastRange===rv&&body.querySelector('.ns-history-kpis'))return;kpiBusy=true;lastRange=rv;try{const d=await get({action:'history',range:rv,type:'all'});const ev=d.events||[];const trips=ev.filter(x=>x.type==='trip').length;const events=ev.filter(x=>x.type==='fuel'||x.type==='issue').length;let host=body.querySelector('.ns-history-kpis');if(!host){host=document.createElement('div');host.className='ns-history-kpis';body.prepend(host)}host.innerHTML=`<div class="ns-history-kpi"><b>${trips.toLocaleString('vi-VN')}</b><span>Tổng số chuyến</span></div><div class="ns-history-kpi"><b>${events.toLocaleString('vi-VN')}</b><span>Sự kiện (Đổ dầu + Sự cố)</span></div>`}catch(e){}finally{kpiBusy=false}}
function apply(){scheduled=false;css();if(!document.getElementById('hist-body'))return;addButtons();refreshKpis(false)}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(apply)}
document.addEventListener('change',e=>{if(e.target?.id==='hist-range')setTimeout(()=>refreshKpis(true),60)},true);
function boot(){apply();new MutationObserver(m=>{if(m.some(x=>x.addedNodes?.length))schedule()}).observe(document.getElementById('screen')||document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();