(function(){
'use strict';
const ACCOUNT_API='https://dnqhikwqihfxvezqzqzn.supabase.co/functions/v1/nghi-son-account-api';
const MAINT_API='https://dnqhikwqihfxvezqzqzn.supabase.co/functions/v1/nghi-son-maintenance-api';
let activeFilter='issue',activePeriod='7days',customFrom='',customTo='',showCount=5;
function esc(v){const d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML}
function token(){return localStorage.getItem('auth_token')||''}
function user(){return Api.getCurrentUser()}
function toast(msg,type){const c=document.getElementById('toast-container');if(!c)return alert(msg);const x=document.createElement('div');x.className='toast '+(type||'')+' show';x.textContent=msg;c.appendChild(x);setTimeout(()=>x.remove(),2800)}
function fmtTime(v){if(!v)return '';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function fmtDate(d){return d.toLocaleDateString('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'})}
function money(v){return Number(v||0).toLocaleString('vi-VN')}
function screen(html){document.getElementById('screen').innerHTML=html;window.scrollTo(0,0)}
function setActive(){document.querySelectorAll('#bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route==='operations-v2'))}
function simpleHeader(title,sub=''){return `<div class="v17-simple-head"><div class="v17-brand-mini">NS</div><div><h2>${esc(title)}</h2><p>${esc(sub)}</p></div></div>`}
function actionBtn(id,icon,label,kind='neutral'){return `<button id="${id}" class="v17-action ${kind}"><span>${icon}</span><b>${esc(label)}</b></button>`}
function field(label,id,type='text',ph=''){return `<div class="v17-field"><label>${esc(label)}</label><input id="${id}" type="${type}" ${type==='number'?'inputmode="decimal" step="0.1"':''} placeholder="${esc(ph)}"></div>`}
function canManage(){return ['ADMIN','MANAGER'].includes(user()?.ROLE)}
function statusLabel(s){return s==='COMPLETED'?'Hoàn thành':s==='CANCELLED'?'Đã hủy':'Tạo mới'}
async function safeGps(){try{return await Gps.getCurrentPosition(7000)}catch(e){return null}}
function gpsText(g){return g?`Đã lấy vị trí · sai số ~${Math.round(g.accuracy||0)} m`:'Không lấy được vị trí · vẫn cho phép lưu'}
async function pickPhoto(label){const input=document.getElementById('camera-input');if(!input||!window.Camera)return null;try{const f=await Camera.pickImage(input);const g=await safeGps();return await Camera.processImage(f,{machineId:label||'',dateTimeText:new Date().toLocaleString('vi-VN'),userName:user()?.FULL_NAME||'',gpsText:g?`${g.latitude.toFixed(5)}, ${g.longitude.toFixed(5)}`:'Không có GPS'});}catch(e){if(e?.code!=='NO_IMAGE')toast(e?.message||'Không xử lý được ảnh.','warning');return null}}
async function maint(action,method='GET',body={}){let r;if(method==='GET'){const q=new URLSearchParams({...body,action,token:token()});r=await fetch(MAINT_API+'?'+q.toString())}else{r=await fetch(MAINT_API+'?action='+encodeURIComponent(action),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,token:token()})})}const j=await r.json();if(!j.success)throw new Error(j.message||'Không xử lý được dữ liệu.');return j.data}
async function accountGet(){const q=new URLSearchParams({action:'account',token:token()});const r=await fetch(ACCOUNT_API+'?'+q.toString());const j=await r.json();if(!j.success)throw new Error(j.message||'Không đọc được tài khoản.');return j.data}
async function tx(action,payload={}){payload.clientTransactionId=payload.clientTransactionId||crypto.randomUUID();if(navigator.onLine){try{return await Api.post(action,payload)}catch(e){if(e&&e.code&&e.code!=='PARSE_ERROR')throw e}}await OfflineQueue.enqueue(action,payload);toast('Đã lưu tạm, sẽ đồng bộ khi có mạng.','warning');return {offline:true}}
async function getRoleContext(){const u=user();if(!u)throw new Error('Chưa đăng nhập.');let selected=null,assets=[];if(['DRIVER','OPERATOR'].includes(u.ROLE)){const acc=await accountGet();selected=acc.selectedAsset||null;assets=(acc.assets||[]).map(x=>({id:x.id,label:x.plate_number||x.name||x.code,type:x.asset_type}))}else{const [v,m]=await Promise.all([Api.get('vehicles',{}),Api.get('machines',{})]);assets=[...(v||[]).map(x=>({id:x.id,label:x.plate_number||x.name||x.code,type:'TRUCK'})),...(m||[]).map(x=>({id:x.MACHINE_UUID||x.id,label:x.MACHINE_NAME||x.name||x.MACHINE_ID||x.code,type:'MACHINE'}))]}return {u,selected,assets}}
function assetSelector(ctx,id='op-asset'){if(ctx.selected)return `<div class="v17-card"><div class="v17-card-title">Phương tiện</div><div class="v17-row"><span>Đang chọn</span><span>${esc(ctx.selected.plate_number||ctx.selected.name||ctx.selected.code)}</span></div></div>`;return `<div class="v17-card"><div class="v17-field"><label>Xe / máy *</label><select id="${id}"><option value="">-- Chọn xe / máy --</option>${ctx.assets.map(x=>`<option value="${esc(x.id)}">${esc(x.label)}</option>`).join('')}</select></div></div>`}
function chosenAsset(ctx,id='op-asset'){return ctx.selected?ctx.selected.id:(document.getElementById(id)?.value||'')}
function isoDate(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function startOfDay(d){const x=new Date(d);x.setHours(0,0,0,0);return x}
function endOfDay(d){const x=new Date(d);x.setHours(23,59,59,999);return x}
function periodBounds(){const now=new Date();if(activePeriod==='today')return [startOfDay(now),now];if(activePeriod==='7days'){const s=startOfDay(now);s.setDate(s.getDate()-6);return [s,now]}if(activePeriod==='month')return [new Date(now.getFullYear(),now.getMonth(),1),now];if(activePeriod==='custom'){const f=customFrom?startOfDay(new Date(customFrom+'T00:00:00')):null;const t=customTo?endOfDay(new Date(customTo+'T00:00:00')):null;return [f,t]}return [null,null]}
function periodText(){const [f,t]=periodBounds();if(!f&&!t)return '';if(activePeriod==='today')return `Hôm nay · ${fmtDate(f)}`;return `${fmtDate(f)} → ${fmtDate(t)}`}
function updateFilterButtons(){document.querySelectorAll('.ops-filter').forEach(b=>{const on=b.dataset.f===activeFilter;b.style.borderColor=on?'#15988f':'#cbd5e1';b.style.color=on?'#0f766e':'#334155';b.style.fontWeight=on?'800':'600';b.style.background=on?'#ecfdf5':'#fff'})}
function renderCustomRange(){const box=document.getElementById('ops-custom-range');if(!box)return;box.style.display=activePeriod==='custom'?'grid':'none';if(activePeriod!=='custom')return;const now=new Date();if(!customTo)customTo=isoDate(now);if(!customFrom){const s=new Date(now);s.setDate(s.getDate()-6);customFrom=isoDate(s)}const f=document.getElementById('ops-from'),t=document.getElementById('ops-to');if(f){f.value=customFrom;f.max=customTo||isoDate(now)}if(t){t.value=customTo;t.min=customFrom;t.max=isoDate(now)}}
async function loadEvents(reset=false){const host=document.getElementById('ops-list');if(!host)return;if(reset)showCount=5;host.innerHTML='<div class="v17-card" style="text-align:center;color:#64748b">Đang tải...</div>';try{const [history,maintRows]=await Promise.all([Api.get('history',{limit:100}),maint('list')]);const fuel=(history||[]).filter(x=>String(x.KIND||x.kind||'').toUpperCase()==='FUEL').map(x=>({kind:'FUEL',time:x.time||x.CREATED_AT,title:x.title||'Đổ dầu',subtitle:x.subtitle||''}));const m=(maintRows||[]).map(x=>({kind:x.type==='REPAIR'?'REPAIR':'ISSUE',time:x.reportedAt,title:(x.type==='REPAIR'?'Sửa chữa ':'Sự cố ')+(x.asset||''),subtitle:x.description||'',status:x.status,statusLabel:x.statusLabel||statusLabel(x.status),id:x.id,assetId:x.assetId,issueId:x.issueId,actualAmount:x.actualAmount}));let rows=[...fuel,...m].sort((a,b)=>+new Date(b.time)-+new Date(a.time));if(activeFilter==='fuel')rows=rows.filter(x=>x.kind==='FUEL');if(activeFilter==='issue')rows=rows.filter(x=>x.kind!=='FUEL');const [from,to]=periodBounds();if(from)rows=rows.filter(x=>new Date(x.time)>=from);if(to)rows=rows.filter(x=>new Date(x.time)<=to);const visible=rows.slice(0,showCount);const meta=document.getElementById('ops-range-label');if(meta)meta.textContent=(periodText()?periodText()+' · ':'')+`${rows.length} bản ghi`;host.innerHTML=visible.length?visible.map(eventHtml).join(''):'<div class="v17-card" style="text-align:center;color:#64748b">Không có dữ liệu trong khoảng thời gian đã chọn.</div>';if(rows.length>showCount)host.insertAdjacentHTML('beforeend',`<button id="ops-more" class="v17-small-btn" style="width:100%;margin-top:4px">Xem thêm (${rows.length-showCount})</button>`);const more=document.getElementById('ops-more');if(more)more.onclick=()=>{showCount+=10;loadEvents(false)};bindMaintenanceActions();updateFilterButtons()}catch(e){host.innerHTML=`<div class="v17-card" style="color:#b91c1c">${esc(e.message||e)}</div>`}}
function eventHtml(x){if(x.kind==='FUEL')return `<div class="v17-event"><div class="ico">⛽</div><div><h4>${esc(x.title)}</h4><p>${esc(x.subtitle)}</p></div><time>${fmtTime(x.time)}</time></div>`;const repair=x.kind==='REPAIR',manage=canManage();const actions=manage&&x.status!=='COMPLETED'&&x.status!=='CANCELLED'?`<div class="v17-inline"><button class="maint-complete" data-id="${x.id}">Hoàn thành</button><button class="maint-cancel" data-id="${x.id}">Đã hủy</button>${!repair?`<button class="maint-repair" data-id="${x.id}" data-asset="${x.assetId}">+ Sửa chữa</button>`:''}</div>`:'';return `<div class="v17-item"><h4>${repair?'🛠️':'🔧'} ${esc(x.title)}</h4><div>${esc(x.subtitle)}</div><div style="margin-top:7px;font-size:13px"><b>Trạng thái:</b> ${esc(x.statusLabel||statusLabel(x.status))}${repair&&x.actualAmount?` · <b>Chi phí:</b> ${money(x.actualAmount)} đ`:''}</div><small>${fmtTime(x.time)}</small>${actions}</div>`}
function bindMaintenanceActions(){document.querySelectorAll('.maint-complete').forEach(b=>b.onclick=async()=>{try{await maint('update-status','POST',{id:b.dataset.id,status:'COMPLETED'});toast('Đã hoàn thành.','success');loadEvents(false)}catch(e){toast(e.message||e,'error')}});document.querySelectorAll('.maint-cancel').forEach(b=>b.onclick=async()=>{const reason=prompt('Nhập lý do hủy *:','');if(!reason||!reason.trim())return toast('Hủy sự cố/sửa chữa phải có lý do.','error');try{await maint('update-status','POST',{id:b.dataset.id,status:'CANCELLED',note:reason.trim()});toast('Đã hủy.','success');loadEvents(false)}catch(e){toast(e.message||e,'error')}});document.querySelectorAll('.maint-repair').forEach(b=>b.onclick=()=>repairForm(b.dataset.id,b.dataset.asset))}
async function renderOperations(){try{setActive();const ctx=await getRoleContext();screen(`<div class="screen">${simpleHeader('Vận hành','Đổ dầu và ghi nhận sự cố')}<div class="v17-wrap"><div class="v17-actions">${actionBtn('all-fuel','⛽','ĐỔ DẦU','teal')}${actionBtn('all-issue','🔧','GHI NHẬN SỰ CỐ','neutral')}</div><div class="v17-card-title" style="margin:22px 2px 9px">TRA CỨU VẬN HÀNH</div><div class="v17-card" style="padding:13px"><div class="v17-field" style="margin-bottom:10px"><label>Thời gian</label><select id="ops-period"><option value="today">Hôm nay</option><option value="7days">7 ngày gần nhất</option><option value="month">Tháng này</option><option value="custom">Từ ngày đến ngày</option></select></div><div id="ops-custom-range" style="display:none;grid-template-columns:1fr 1fr;gap:10px"><div class="v17-field"><label>Từ ngày</label><input id="ops-from" type="date"></div><div class="v17-field"><label>Đến ngày</label><input id="ops-to" type="date"></div><button id="ops-apply-range" class="v17-small-btn" style="grid-column:1/-1">Áp dụng khoảng ngày</button></div><div id="ops-range-label" style="font-size:12px;color:#64748b"></div></div><div class="v17-inline" style="margin:0 0 12px"><button class="ops-filter" data-f="issue">🔧 Sự cố / sửa chữa</button><button class="ops-filter" data-f="fuel">⛽ Đổ dầu</button><button class="ops-filter" data-f="all">Tất cả</button></div><div class="v17-card-title" style="margin:14px 2px 9px">5 BẢN GHI GẦN NHẤT</div><div id="ops-list"></div></div></div>`);document.getElementById('all-fuel').onclick=()=>fuelForm(ctx);document.getElementById('all-issue').onclick=()=>issueForm(ctx);const p=document.getElementById('ops-period');p.value=activePeriod;p.onchange=()=>{activePeriod=p.value;renderCustomRange();if(activePeriod!=='custom')loadEvents(true)};document.querySelectorAll('.ops-filter').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.f;loadEvents(true)});document.getElementById('ops-apply-range').onclick=()=>{const f=document.getElementById('ops-from').value,t=document.getElementById('ops-to').value;if(!f||!t)return toast('Vui lòng chọn đủ từ ngày và đến ngày.','warning');if(f>t)return toast('Từ ngày không được sau đến ngày.','warning');customFrom=f;customTo=t;loadEvents(true)};document.getElementById('ops-from').onchange=e=>{customFrom=e.target.value;if(customTo&&customFrom>customTo)customTo=customFrom;renderCustomRange()};document.getElementById('ops-to').onchange=e=>{customTo=e.target.value;if(customFrom&&customTo<customFrom)customFrom=customTo;renderCustomRange()};renderCustomRange();updateFilterButtons();loadEvents(true)}catch(e){screen(`<div class="screen">${simpleHeader('Vận hành','')}<div class="v17-wrap"><div class="v17-card" style="color:#b91c1c">${esc(e.message||e)}</div></div></div>`)}}
function fuelForm(ctx){let photo=null;screen(`<div class="screen">${simpleHeader('Đổ dầu','Số lít và công tơ mét/giờ máy là bắt buộc')}<div class="v17-wrap">${assetSelector(ctx)}<div class="v17-card">${field('Số lít *','fuel-q','number')}${field('Công tơ mét / giờ máy *','fuel-meter','number')}${field('Ghi chú','fuel-note')}<button class="v17-small-btn" id="fuel-photo">📷 Ảnh đính kèm (không bắt buộc)</button><div id="fuel-photo-state" style="font-size:12px;color:#64748b;margin-top:8px"></div></div>${actionBtn('fuel-save-all','⛽','XÁC NHẬN ĐỔ DẦU','teal')}<button class="v17-small-btn" id="ops-back" style="margin-top:10px">Quay lại</button></div></div>`);document.getElementById('ops-back').onclick=renderOperations;document.getElementById('fuel-photo').onclick=async()=>{photo=await pickPhoto(ctx.selected?.plate_number||ctx.selected?.name||'Nghi Sơn');document.getElementById('fuel-photo-state').textContent=photo?'Đã chọn 1 ảnh.':''};document.getElementById('fuel-save-all').onclick=async()=>{const aid=chosenAsset(ctx),q=Number(document.getElementById('fuel-q').value||0),meter=Number(document.getElementById('fuel-meter').value||0);if(!aid)return toast('Vui lòng chọn xe / máy.','error');if(q<=0)return toast('Số lít phải lớn hơn 0.','error');if(meter<=0)return toast('Công tơ mét / giờ máy là bắt buộc.','error');const g=await safeGps();toast(gpsText(g),g?'success':'warning');try{await tx('fuel',{quantity:q,hourMeter:meter,odometer:meter,note:document.getElementById('fuel-note').value,vehicleId:aid,machineId:aid,lat:g?.latitude||null,lng:g?.longitude||null,gpsStatus:g?'OK':'MISSING',imageReceipt:photo||null});toast('Đã ghi nhận đổ dầu.','success');renderOperations()}catch(e){toast(e.message||e,'error')}}}
function issueForm(ctx){let photo=null;screen(`<div class="screen">${simpleHeader('Ghi nhận sự cố','Mô tả bắt buộc; GPS và ảnh không chặn thao tác')}<div class="v17-wrap">${assetSelector(ctx)}<div class="v17-card">${field('Loại sự cố','issue-type-all','text','Lốp, động cơ, phanh...')}${field('Mô tả *','issue-desc-all')}<div class="v17-field"><label>Mức độ</label><select id="issue-sev-all"><option value="LOW">Vẫn hoạt động</option><option value="MEDIUM">Hoạt động hạn chế</option><option value="HIGH">Phải dừng</option></select></div><button class="v17-small-btn" id="issue-photo">📷 Ảnh sự cố (không bắt buộc)</button><div id="issue-photo-state" style="font-size:12px;color:#64748b;margin-top:8px"></div></div>${actionBtn('issue-save-all','🔧','GHI NHẬN SỰ CỐ','neutral')}<button class="v17-small-btn" id="ops-back" style="margin-top:10px">Quay lại</button></div></div>`);document.getElementById('ops-back').onclick=renderOperations;document.getElementById('issue-photo').onclick=async()=>{photo=await pickPhoto(ctx.selected?.plate_number||ctx.selected?.name||'Nghi Sơn');document.getElementById('issue-photo-state').textContent=photo?'Đã chọn 1 ảnh.':''};document.getElementById('issue-save-all').onclick=async()=>{const aid=chosenAsset(ctx),d=document.getElementById('issue-desc-all').value.trim();if(!aid)return toast('Vui lòng chọn xe / máy.','error');if(!d)return toast('Vui lòng nhập mô tả sự cố.','error');const g=await safeGps();toast(gpsText(g),g?'success':'warning');try{await tx('issue',{vehicleId:aid,machineId:aid,issueType:document.getElementById('issue-type-all').value,severity:document.getElementById('issue-sev-all').value,description:d,lat:g?.latitude||null,lng:g?.longitude||null,gpsStatus:g?'OK':'MISSING',images:photo?[photo]:[]});toast('Đã ghi nhận sự cố. Trạng thái: Tạo mới.','success');renderOperations()}catch(e){toast(e.message||e,'error')}}}
function repairForm(issueId,assetId){screen(`<div class="screen">${simpleHeader('Ghi sửa chữa','Theo dõi sửa chữa nội bộ')}<div class="v17-wrap"><div class="v17-card">${field('Nội dung sửa chữa *','repair-desc')}${field('Người / đơn vị thực hiện','repair-vendor')}${field('Chi phí thực tế','repair-cost','number')}${field('Ghi chú','repair-note')}</div>${actionBtn('repair-save','🛠️','LƯU SỬA CHỮA','teal')}<button class="v17-small-btn" id="repair-back" style="margin-top:10px">Quay lại</button></div></div>`);document.getElementById('repair-back').onclick=renderOperations;document.getElementById('repair-save').onclick=async()=>{const d=document.getElementById('repair-desc').value.trim();if(!d)return toast('Vui lòng nhập nội dung sửa chữa.','error');try{await maint('repair/create','POST',{issueId,assetId,description:d,vendor:document.getElementById('repair-vendor').value,actualAmount:Number(document.getElementById('repair-cost').value||0)||null,note:document.getElementById('repair-note').value});toast('Đã tạo bản ghi sửa chữa. Trạng thái: Tạo mới.','success');renderOperations()}catch(e){toast(e.message||e,'error')}}}
document.addEventListener('click',e=>{const b=e.target.closest('#bottom-nav button[data-route="operations-v2"]');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();renderOperations()},true);
window.NSOperationsV20={render:renderOperations};
})();