(function(){
'use strict';
const ACCOUNT_API='https://dnqhikwqihfxvezqzqzn.supabase.co/functions/v1/nghi-son-account-api';
const MAINT_API='https://dnqhikwqihfxvezqzqzn.supabase.co/functions/v1/nghi-son-maintenance-api';
function esc(v){const d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML}
function token(){return localStorage.getItem('auth_token')||''}
function user(){return Api.getCurrentUser()}
function toast(msg,type){const c=document.getElementById('toast-container');if(!c)return alert(msg);const x=document.createElement('div');x.className='toast '+(type||'')+' show';x.textContent=msg;c.appendChild(x);setTimeout(()=>x.remove(),2600)}
function fmtTime(v){if(!v)return '';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function money(v){return Number(v||0).toLocaleString('vi-VN')}
function screen(html){document.getElementById('screen').innerHTML=html;window.scrollTo(0,0)}
function setActive(){document.querySelectorAll('#bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route==='operations-v2'))}
function simpleHeader(title,sub=''){return `<div class="v17-simple-head"><div class="v17-brand-mini">NS</div><div><h2>${esc(title)}</h2><p>${esc(sub)}</p></div></div>`}
function actionBtn(id,icon,label,kind='neutral'){return `<button id="${id}" class="v17-action ${kind}"><span>${icon}</span><b>${esc(label)}</b></button>`}
function field(label,id,type='text',ph=''){return `<div class="v17-field"><label>${esc(label)}</label><input id="${id}" type="${type}" ${type==='number'?'inputmode="decimal" step="0.1"':''} placeholder="${esc(ph)}"></div>`}
function canManage(){return ['ADMIN','MANAGER'].includes(user()?.ROLE)}
function statusLabel(s){return s==='COMPLETED'?'Hoàn thành':s==='CANCELLED'?'Đã hủy':'Tạo mới'}
async function maint(action,method='GET',body={}){let r;if(method==='GET'){const q=new URLSearchParams({...body,action,token:token()});r=await fetch(MAINT_API+'?'+q.toString())}else{r=await fetch(MAINT_API+'?action='+encodeURIComponent(action),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,token:token()})})}const j=await r.json();if(!j.success)throw new Error(j.message||'Không xử lý được dữ liệu.');return j.data}
async function accountGet(){const q=new URLSearchParams({action:'account',token:token()});const r=await fetch(ACCOUNT_API+'?'+q.toString());const j=await r.json();if(!j.success)throw new Error(j.message||'Không đọc được tài khoản.');return j.data}
async function tx(action,payload={}){payload.clientTransactionId=payload.clientTransactionId||crypto.randomUUID();if(navigator.onLine){try{return await Api.post(action,payload)}catch(e){if(e&&e.code&&e.code!=='PARSE_ERROR')throw e}}await OfflineQueue.enqueue(action,payload);toast('Đã lưu tạm, sẽ đồng bộ khi có mạng.','warning');return {offline:true}}
async function getRoleContext(){const u=user();if(!u)throw new Error('Chưa đăng nhập.');let selected=null,assets=[];if(['DRIVER','OPERATOR'].includes(u.ROLE)){const acc=await accountGet();selected=acc.selectedAsset||null;assets=(acc.assets||[]).map(x=>({id:x.id,label:x.plate_number||x.name||x.code,type:x.asset_type}))}else{const [v,m]=await Promise.all([Api.get('vehicles',{}),Api.get('machines',{})]);assets=[...(v||[]).map(x=>({id:x.id,label:x.plate_number||x.name||x.code,type:'TRUCK'})),...(m||[]).map(x=>({id:x.MACHINE_UUID||x.id,label:x.MACHINE_NAME||x.name||x.MACHINE_ID||x.code,type:'MACHINE'}))]}return {u,selected,assets}}
function assetSelector(ctx,id='op-asset'){if(ctx.selected)return `<div class="v17-card"><div class="v17-card-title">Phương tiện</div><div class="v17-row"><span>Đang chọn</span><span>${esc(ctx.selected.plate_number||ctx.selected.name||ctx.selected.code)}</span></div></div>`;return `<div class="v17-card"><div class="v17-field"><label>Xe / máy *</label><select id="${id}"><option value="">-- Chọn xe / máy --</option>${ctx.assets.map(x=>`<option value="${esc(x.id)}">${esc(x.label)}</option>`).join('')}</select></div></div>`}
function chosenAsset(ctx,id='op-asset'){if(ctx.selected)return ctx.selected.id;return document.getElementById(id)?.value||''}
async function loadEvents(filter='all'){
 const host=document.getElementById('ops-list');if(!host)return;host.innerHTML='<div class="v17-card" style="text-align:center;color:#64748b">Đang tải...</div>';
 try{
  const [history,maintRows]=await Promise.all([Api.get('history',{limit:100}),maint('list')]);
  const fuel=(history||[]).filter(x=>String(x.KIND||x.kind||'').toUpperCase()==='FUEL').map(x=>({kind:'FUEL',time:x.time||x.CREATED_AT,title:x.title||'Đổ dầu',subtitle:x.subtitle||''}));
  const m=(maintRows||[]).map(x=>({kind:x.type==='REPAIR'?'REPAIR':'ISSUE',time:x.reportedAt,title:(x.type==='REPAIR'?'Sửa chữa ':'Sự cố ')+(x.asset||''),subtitle:x.description||'',status:x.status,statusLabel:x.statusLabel||statusLabel(x.status),id:x.id,assetId:x.assetId,issueId:x.issueId,vendor:x.vendor,actualAmount:x.actualAmount}));
  let rows=[...fuel,...m].sort((a,b)=>+new Date(b.time)-+new Date(a.time));
  if(filter==='fuel')rows=rows.filter(x=>x.kind==='FUEL');
  if(filter==='issue')rows=rows.filter(x=>x.kind!=='FUEL');
  host.innerHTML=rows.length?rows.slice(0,50).map(x=>eventHtml(x)).join(''):'<div class="v17-card" style="text-align:center;color:#64748b">Chưa có dữ liệu.</div>';
  bindMaintenanceActions();
 }catch(e){host.innerHTML=`<div class="v17-card" style="color:#b91c1c">${esc(e.message||e)}</div>`}
}
function eventHtml(x){
 if(x.kind==='FUEL')return `<div class="v17-event"><div class="ico">⛽</div><div><h4>${esc(x.title)}</h4><p>${esc(x.subtitle)}</p></div><time>${fmtTime(x.time)}</time></div>`;
 const repair=x.kind==='REPAIR';const manage=canManage();const actions=manage&&x.status!=='COMPLETED'&&x.status!=='CANCELLED'?`<div class="v17-inline"><button class="maint-complete" data-id="${x.id}">Hoàn thành</button><button class="maint-cancel" data-id="${x.id}">Đã hủy</button>${!repair?`<button class="maint-repair" data-id="${x.id}" data-asset="${x.assetId}">+ Sửa chữa</button>`:''}</div>`:'';
 return `<div class="v17-item"><h4>${repair?'🛠️':'🔧'} ${esc(x.title)}</h4><div>${esc(x.subtitle)}</div><div style="margin-top:7px;font-size:13px"><b>Trạng thái:</b> ${esc(x.statusLabel||statusLabel(x.status))}${repair&&x.actualAmount?` · <b>Chi phí:</b> ${money(x.actualAmount)} đ`:''}</div><small>${fmtTime(x.time)}</small>${actions}</div>`
}
function bindMaintenanceActions(){
 document.querySelectorAll('.maint-complete').forEach(b=>b.onclick=async()=>{try{await maint('update-status','POST',{id:b.dataset.id,status:'COMPLETED'});toast('Đã chuyển trạng thái Hoàn thành.','success');loadEvents('issue')}catch(e){toast(e.message||e,'error')}});
 document.querySelectorAll('.maint-cancel').forEach(b=>b.onclick=async()=>{try{await maint('update-status','POST',{id:b.dataset.id,status:'CANCELLED'});toast('Đã chuyển trạng thái Đã hủy.','success');loadEvents('issue')}catch(e){toast(e.message||e,'error')}});
 document.querySelectorAll('.maint-repair').forEach(b=>b.onclick=()=>repairForm(b.dataset.id,b.dataset.asset));
}
async function renderOperations(){try{setActive();const ctx=await getRoleContext();screen(`<div class="screen">${simpleHeader('Vận hành','Đổ dầu và ghi nhận sự cố')}<div class="v17-wrap"><div class="v17-actions">${actionBtn('all-fuel','⛽','ĐỔ DẦU','teal')}${actionBtn('all-issue','🔧','GHI NHẬN SỰ CỐ','neutral')}</div><div class="v17-card-title" style="margin:22px 2px 9px">DANH SÁCH GẦN NHẤT</div><div class="v17-inline" style="margin:0 0 12px"><button class="ops-filter" data-f="all">Tất cả</button><button class="ops-filter" data-f="fuel">⛽ Đổ dầu</button><button class="ops-filter" data-f="issue">🔧 Sự cố / sửa chữa</button></div><div id="ops-list"></div></div></div>`);document.getElementById('all-fuel').onclick=()=>fuelForm(ctx);document.getElementById('all-issue').onclick=()=>issueForm(ctx);document.querySelectorAll('.ops-filter').forEach(b=>b.onclick=()=>loadEvents(b.dataset.f));loadEvents('all')}catch(e){screen(`<div class="screen">${simpleHeader('Vận hành','')}<div class="v17-wrap"><div class="v17-card" style="color:#b91c1c">${esc(e.message||e)}</div></div></div>`)}}
function fuelForm(ctx){screen(`<div class="screen">${simpleHeader('Đổ dầu','Ghi nhận cho xe / máy')}<div class="v17-wrap">${assetSelector(ctx)}<div class="v17-card">${field('Số lít *','fuel-q','number')}${field('Công tơ mét / giờ máy','fuel-meter','number')}${field('Ghi chú','fuel-note')}</div>${actionBtn('fuel-save-all','⛽','XÁC NHẬN ĐỔ DẦU','teal')}<button class="v17-small-btn" id="ops-back" style="margin-top:10px">Quay lại</button></div></div>`);document.getElementById('ops-back').onclick=renderOperations;document.getElementById('fuel-save-all').onclick=async()=>{const aid=chosenAsset(ctx),q=Number(document.getElementById('fuel-q').value||0);if(!aid)return toast('Vui lòng chọn xe / máy.','error');if(q<=0)return toast('Vui lòng nhập số lít.','error');try{await tx('fuel',{quantity:q,hourMeter:Number(document.getElementById('fuel-meter').value||0)||null,note:document.getElementById('fuel-note').value,vehicleId:aid,machineId:aid});toast('Đã ghi nhận đổ dầu.','success');renderOperations()}catch(e){toast(e.message||e,'error')}}}
function issueForm(ctx){screen(`<div class="screen">${simpleHeader('Ghi nhận sự cố','Ghi nhận cho xe / máy')}<div class="v17-wrap">${assetSelector(ctx)}<div class="v17-card">${field('Loại sự cố','issue-type-all','text','Lốp, động cơ, phanh...')}${field('Mô tả *','issue-desc-all')}<div class="v17-field"><label>Mức độ</label><select id="issue-sev-all"><option value="LOW">Vẫn hoạt động</option><option value="MEDIUM">Hoạt động hạn chế</option><option value="HIGH">Phải dừng</option></select></div></div>${actionBtn('issue-save-all','🔧','GHI NHẬN SỰ CỐ','neutral')}<button class="v17-small-btn" id="ops-back" style="margin-top:10px">Quay lại</button></div></div>`);document.getElementById('ops-back').onclick=renderOperations;document.getElementById('issue-save-all').onclick=async()=>{const aid=chosenAsset(ctx),d=document.getElementById('issue-desc-all').value.trim();if(!aid)return toast('Vui lòng chọn xe / máy.','error');if(!d)return toast('Vui lòng nhập mô tả sự cố.','error');try{await tx('issue',{vehicleId:aid,machineId:aid,issueType:document.getElementById('issue-type-all').value,severity:document.getElementById('issue-sev-all').value,description:d});toast('Đã ghi nhận sự cố. Trạng thái: Tạo mới.','success');renderOperations()}catch(e){toast(e.message||e,'error')}}}
function repairForm(issueId,assetId){screen(`<div class="screen">${simpleHeader('Ghi sửa chữa','Theo dõi sửa chữa nội bộ')}<div class="v17-wrap"><div class="v17-card">${field('Nội dung sửa chữa *','repair-desc')}${field('Người / đơn vị thực hiện','repair-vendor')}${field('Chi phí thực tế','repair-cost','number')}${field('Ghi chú','repair-note')}</div>${actionBtn('repair-save','🛠️','LƯU SỬA CHỮA','teal')}<button class="v17-small-btn" id="repair-back" style="margin-top:10px">Quay lại</button></div></div>`);document.getElementById('repair-back').onclick=renderOperations;document.getElementById('repair-save').onclick=async()=>{const d=document.getElementById('repair-desc').value.trim();if(!d)return toast('Vui lòng nhập nội dung sửa chữa.','error');try{await maint('repair/create','POST',{issueId,assetId,description:d,vendor:document.getElementById('repair-vendor').value,actualAmount:Number(document.getElementById('repair-cost').value||0)||null,note:document.getElementById('repair-note').value});toast('Đã tạo bản ghi sửa chữa. Trạng thái: Tạo mới.','success');renderOperations()}catch(e){toast(e.message||e,'error')}}}
document.addEventListener('click',e=>{const b=e.target.closest('#bottom-nav button[data-route="operations-v2"]');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();renderOperations()},true);
window.NSOperationsV19={render:renderOperations};
})();