(function(){
function user(){return window.Api&&Api.getCurrentUser?Api.getCurrentUser():null}
function esc(s){var d=document.createElement('div');d.textContent=s==null?'':String(s);return d.innerHTML}
function toast(s,type){var c=document.getElementById('toast-container');if(!c)return;var x=document.createElement('div');x.className='toast '+(type||'success')+' show';x.textContent=s;c.appendChild(x);setTimeout(()=>x.remove(),2600)}
async function gps(){try{return await Gps.getCurrentPosition()}catch(e){return null}}
async function tx(action,payload){payload=payload||{};payload.clientTransactionId=payload.clientTransactionId||crypto.randomUUID();if(navigator.onLine){try{return await Api.post(action,payload)}catch(e){if(e&&e.code&&e.code!=='PARSE_ERROR')throw e}}await OfflineQueue.enqueue(action,payload);toast('Đã lưu tạm, sẽ đồng bộ khi có mạng.','warning');return {offline:true}}
function screen(title,html){document.getElementById('role-v2-panel')?.remove();var d=document.createElement('div');d.id='role-v2-panel';d.style.cssText='position:fixed;inset:0;z-index:9000;background:#f5f7f9;overflow:auto;padding:16px 14px 90px';d.innerHTML='<div style="max-width:620px;margin:auto"><div style="display:flex;align-items:center;gap:8px"><button id="rv-back" style="border:0;background:none;font-size:26px">←</button><h2 style="margin:8px 0">'+title+'</h2></div>'+html+'</div>';document.body.appendChild(d);d.querySelector('#rv-back').onclick=()=>d.remove();return d}
function field(label,id,type,ph){return '<label style="font-weight:700">'+label+'</label><input id="'+id+'" type="'+(type||'text')+'" placeholder="'+(ph||'')+'" style="width:100%;box-sizing:border-box;padding:12px;margin:6px 0 12px;border:1px solid #d1d5db;border-radius:10px;font-size:16px">'}
function select(label,id,items,fmt){return '<label style="font-weight:700">'+label+'</label><select id="'+id+'" style="width:100%;padding:12px;margin:6px 0 12px;border:1px solid #d1d5db;border-radius:10px;font-size:16px"><option value="">-- Chọn --</option>'+items.map(x=>'<option value="'+x.id+'">'+esc(fmt(x))+'</option>').join('')+'</select>'}
function btn(id,text,danger){return '<button id="'+id+'" style="width:100%;padding:14px;margin:6px 0;border:0;border-radius:12px;background:'+(danger?'#dc2626':'#12998f')+';color:white;font-weight:800;font-size:16px">'+text+'</button>'}
async function renderDriver(){var d=screen('Vận tải','<div id="rv-load">Đang tải...</div>');try{var h=await Api.get('home',{});var c=h.currentTrip;if(c){d.querySelector('#rv-load').innerHTML='<div style="background:white;padding:15px;border-radius:14px"><b>🚚 '+esc(c.PLATE_NUMBER||c.VEHICLE_ID)+'</b><p>'+esc(c.ROUTE_NAME||'')+'</p><p>'+esc(c.ORIGIN||'')+' → '+esc(c.DESTINATION||'')+'</p><p>Trạng thái: <b>Đang chạy</b></p>'+btn('complete','HOÀN THÀNH CHUYẾN')+btn('operations','VẬN HÀNH')+'</div>';d.querySelector('#complete').onclick=async()=>{var g=await gps();await tx('trip/complete',{lat:g?.latitude,lng:g?.longitude});d.remove();setTimeout(renderDriver,300)};d.querySelector('#operations').onclick=()=>openOperations();return}
var vehicles=h.vehicles||[],routes=h.routes||[];d.querySelector('#rv-load').innerHTML='<div style="background:white;padding:15px;border-radius:14px">'+select('Xe','vehicle',vehicles,x=>(x.plate_number||x.code)+' - '+(x.name||''))+select('Tuyến','route',routes,x=>x.name+' · '+x.origin+' → '+x.destination)+field('Loại hàng (nếu khác mặc định)','cargo')+btn('start','BẮT ĐẦU CHUYẾN')+'</div>';d.querySelector('#start').onclick=async()=>{var vehicleId=d.querySelector('#vehicle').value,routeId=d.querySelector('#route').value;if(!vehicleId||!routeId)return alert('Vui lòng chọn xe và tuyến.');var g=await gps();await tx('trip/start',{vehicleId,routeId,cargoType:d.querySelector('#cargo').value,lat:g?.latitude,lng:g?.longitude});d.remove();setTimeout(renderDriver,300)}}catch(e){d.querySelector('#rv-load').innerHTML='<div style="color:red">'+esc(e.message||e)+'</div>'}}
async function renderOperator(){var d=screen('Vận hành máy','<div id="rv-load">Đang tải...</div>');try{var h=await Api.get('home',{});var c=h.currentShift;if(c){d.querySelector('#rv-load').innerHTML='<div style="background:white;padding:15px;border-radius:14px"><b>🚜 '+esc(c.MACHINE_ID)+'</b><p>'+esc(c.WORK_TYPE_NAME||'')+'</p><p>Bắt đầu: '+new Date(c.START_AT).toLocaleString('vi-VN')+'</p>'+field('Giờ máy cuối','endmeter','number')+btn('end','KẾT THÚC CA')+btn('operations','VẬN HÀNH')+'</div>';d.querySelector('#end').onclick=async()=>{var g=await gps();await tx('shift/end',{endHourMeter:Number(d.querySelector('#endmeter').value||0)||null,lat:g?.latitude,lng:g?.longitude});d.remove();setTimeout(renderOperator,300)};d.querySelector('#operations').onclick=()=>openOperations();return}
var machines=h.machines||[],works=h.workTypes||[];d.querySelector('#rv-load').innerHTML='<div style="background:white;padding:15px;border-radius:14px">'+select('Máy','machine',machines,x=>x.code+' - '+x.name)+select('Loại công việc','work',works,x=>x.name)+field('Giờ máy đầu','startmeter','number')+btn('start','BẮT ĐẦU CA')+'</div>';d.querySelector('#start').onclick=async()=>{var machineId=d.querySelector('#machine').value,workTypeId=d.querySelector('#work').value;if(!machineId||!workTypeId)return alert('Vui lòng chọn máy và loại công việc.');var g=await gps();await tx('shift/start',{machineId,workTypeId,startHourMeter:Number(d.querySelector('#startmeter').value||0)||null,lat:g?.latitude,lng:g?.longitude});d.remove();setTimeout(renderOperator,300)}}catch(e){d.querySelector('#rv-load').innerHTML='<div style="color:red">'+esc(e.message||e)+'</div>'}}
function openFuel(){var d=screen('Đổ dầu','<div style="background:white;padding:15px;border-radius:14px">'+field('Số lít *','qty','number')+field('Công tơ mét / giờ máy','meter','number')+field('Ghi chú','note')+btn('save','GHI NHẬN ĐỔ DẦU')+'</div>');d.querySelector('#save').onclick=async()=>{var q=Number(d.querySelector('#qty').value||0);if(q<=0)return alert('Số lít phải lớn hơn 0.');await tx('fuel',{quantity:q,hourMeter:Number(d.querySelector('#meter').value||0)||null,note:d.querySelector('#note').value});toast('Đã ghi nhận đổ dầu.');d.remove()}}
function openIssue(){var d=screen('Báo sự cố','<div style="background:white;padding:15px;border-radius:14px">'+field('Loại sự cố','type','text','Động cơ, thủy lực...')+field('Mô tả *','desc')+'<label style="font-weight:700">Mức độ</label><select id="sev" style="width:100%;padding:12px;margin:6px 0 12px"><option value="LOW">Vẫn hoạt động</option><option value="MEDIUM">Hoạt động hạn chế</option><option value="HIGH">Phải dừng xe/máy</option></select>'+btn('save','GỬI GHI NHẬN',true)+'</div>');d.querySelector('#save').onclick=async()=>{var desc=d.querySelector('#desc').value.trim();if(!desc)return alert('Vui lòng nhập mô tả.');await tx('issue',{issueType:d.querySelector('#type').value,severity:d.querySelector('#sev').value,description:desc});toast('Đã ghi nhận sự cố.');d.remove()}}
async function openStopIncident(){var d=screen('Dừng xe do sự cố','<div style="background:white;padding:15px;border-radius:14px"><p style="margin-top:0;color:#6b7280">Dùng khi xe đang chạy và phải dừng vì sự cố. Hệ thống sẽ vừa dừng chuyến, vừa tạo ghi nhận sự cố.</p>'+field('Loại sự cố','type','text','Lốp, động cơ, phanh...')+field('Mô tả *','desc')+btn('save','DỪNG XE VÀ GHI NHẬN',true)+'</div>');d.querySelector('#save').onclick=async()=>{var desc=d.querySelector('#desc').value.trim();if(!desc)return alert('Vui lòng nhập mô tả sự cố.');var g=await gps();await tx('trip/pause',{reason:'INCIDENT',note:desc,lat:g?.latitude,lng:g?.longitude});await tx('issue',{issueType:d.querySelector('#type').value,severity:'HIGH',description:desc,lat:g?.latitude,lng:g?.longitude});toast('Đã dừng chuyến và ghi nhận sự cố.');d.remove()}}
async function openOperations(){var u=user();var d=screen('Vận hành','<div id="rv-load">Đang tải...</div>');try{var html='<div style="background:white;padding:15px;border-radius:14px"><p style="margin-top:0;color:#6b7280">Các nghiệp vụ phát sinh trong quá trình vận hành.</p>'+btn('fuel','⛽ ĐỔ DẦU')+btn('issue','🔧 GHI NHẬN SỰ CỐ');if(u&&u.ROLE==='DRIVER'){var h=await Api.get('home',{});if(h.currentTrip)html+=btn('stop','⛔ DỪNG XE DO SỰ CỐ',true)}html+='</div>';d.querySelector('#rv-load').innerHTML=html;d.querySelector('#fuel').onclick=openFuel;d.querySelector('#issue').onclick=openIssue;var sb=d.querySelector('#stop');if(sb)sb.onclick=openStopIncident}catch(e){d.querySelector('#rv-load').innerHTML='<div style="color:red">'+esc(e.message||e)+'</div>'}}
async function openReport(){var d=screen('Báo cáo','<div id="rv-load">Đang tải...</div>');try{var now=new Date(),from=new Date(now.getFullYear(),now.getMonth(),1).toISOString().slice(0,10),to=now.toISOString().slice(0,10);var r=await Api.get('report/summary',{from:from,to:to});d.querySelector('#rv-load').innerHTML='<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><div class="stat-card"><b>'+r.trips+'</b><div>Chuyến</div></div><div class="stat-card"><b>'+r.completedTrips+'</b><div>Hoàn thành</div></div><div class="stat-card"><b>'+Number(r.fuelLiters||0).toLocaleString('vi-VN')+'</b><div>Lít dầu</div></div><div class="stat-card"><b>'+r.openIssues+'</b><div>Sự cố mở</div></div></div><p style="font-size:13px;color:#6b7280">Từ '+from+' đến '+to+'</p>'}catch(e){d.querySelector('#rv-load').innerHTML='<div style="color:red">'+esc(e.message||e)+'</div>'}}
function maybeHome(){var u=user();if(!u||document.getElementById('role-v2-panel'))return;var home=document.querySelector('#bottom-nav button[data-route="home"].active');if(!home)return;if(u.ROLE==='DRIVER'){var s=document.getElementById('screen');if(s&&s.dataset.roleV2!=='DRIVER'){s.dataset.roleV2='DRIVER';setTimeout(renderDriver,50)}}else if(u.ROLE==='OPERATOR'){var s2=document.getElementById('screen');if(s2&&s2.dataset.roleV2!=='OPERATOR'){s2.dataset.roleV2='OPERATOR';setTimeout(renderOperator,50)}}}
document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('#bottom-nav button[data-route="operations-v2"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();openOperations()},true);
document.addEventListener('DOMContentLoaded',function(){new MutationObserver(()=>setTimeout(maybeHome,50)).observe(document.getElementById('screen'),{childList:true,subtree:true});setTimeout(maybeHome,300)});
window.NSRoleV2={openDriver:renderDriver,openOperator:renderOperator,openReport:openReport,openOperations:openOperations,openFuel:openFuel,openIssue:openIssue,openStopIncident:openStopIncident};
})();