(function(){
  var busy=false;
  function user(){return window.Api&&Api.getCurrentUser?Api.getCurrentUser():null}
  function esc(s){var d=document.createElement('div');d.textContent=s==null?'':String(s);return d.innerHTML}
  function toast(msg,type){var c=document.getElementById('toast-container');if(!c)return;var x=document.createElement('div');x.className='toast '+(type||'')+' show';x.textContent=msg;c.appendChild(x);setTimeout(function(){x.remove()},2800)}
  function active(route){document.querySelectorAll('#bottom-nav button').forEach(function(b){b.classList.toggle('active',b.dataset.route===route)})}
  async function gps(){try{return await Gps.getCurrentPosition()}catch(e){return null}}
  async function tx(action,payload){payload=payload||{};payload.clientTransactionId=payload.clientTransactionId||crypto.randomUUID();if(navigator.onLine){try{return await Api.post(action,payload)}catch(e){if(e&&e.code&&e.code!=='PARSE_ERROR')throw e}}await OfflineQueue.enqueue(action,payload);toast('Đã lưu tạm, sẽ đồng bộ khi có mạng.','warning');return {offline:true}}
  function selectHtml(label,id,items,fmt){return '<div class="field"><label>'+label+'</label><select class="select-field" id="'+id+'"><option value="">-- Chọn --</option>'+items.map(function(x){return '<option value="'+x.id+'">'+esc(fmt(x))+'</option>'}).join('')+'</select></div>'}
  function inputHtml(label,id,type,ph){return '<div class="field"><label>'+label+'</label><input id="'+id+'" type="'+(type||'text')+'" '+(type==='number'?'inputmode="decimal" step="0.1"':'')+' placeholder="'+esc(ph||'')+'"></div>'}
  function shell(title,subtitle,body){return '<div class="screen"><div class="app-header"><p class="greeting">'+esc(subtitle||'')+'</p><p class="user-name">'+esc(title)+'</p></div><div class="action-list" style="padding-top:18px">'+body+'</div></div>'}
  function ensureNav(){var nav=document.getElementById('bottom-nav');if(nav)nav.classList.remove('hidden')}

  async function renderHome(){
    var u=user();if(!u||!['DRIVER','OPERATOR'].includes(u.ROLE))return false;
    busy=true;ensureNav();active('home');var s=document.getElementById('screen');s.innerHTML=shell(u.FULL_NAME,u.ROLE==='DRIVER'?'Tài xế xe tải':'Lái xe công trình','<div class="loading-wrap"><div class="spinner"></div> Đang tải...</div>');
    try{
      var h=await Api.get('home',{}),html='';
      if(u.ROLE==='DRIVER'){
        if(h.currentTrip){var c=h.currentTrip;html='<div class="account-card"><p class="name">🚚 '+esc(c.PLATE_NUMBER||c.VEHICLE_ID)+'</p><div class="detail-row"><span>Tuyến</span><span>'+esc(c.ROUTE_NAME||'—')+'</span></div><div class="detail-row"><span>Hành trình</span><span>'+esc((c.ORIGIN||'')+' → '+(c.DESTINATION||''))+'</span></div><div class="detail-row"><span>Trạng thái</span><span>Đang chạy</span></div></div><button class="btn-big primary" id="main-finish"><span class="icon">⏹</span><span>KẾT THÚC CHUYẾN</span></button>'}
        else{html='<div class="account-card">'+selectHtml('Xe tải','main-vehicle',h.vehicles||[],function(x){return (x.plate_number||x.code)+(x.name?' - '+x.name:'')})+selectHtml('Tuyến','main-route',h.routes||[],function(x){return x.name+' · '+x.origin+' → '+x.destination})+'</div><button class="btn-big primary" id="main-start"><span class="icon">▶</span><span>BẮT ĐẦU CHUYẾN</span></button>'}
      }else{
        if(h.currentShift){var c2=h.currentShift;html='<div class="account-card"><p class="name">🚜 '+esc(c2.MACHINE_NAME||c2.MACHINE_ID)+'</p><div class="detail-row"><span>Công việc</span><span>'+esc(c2.WORK_TYPE_NAME||'—')+'</span></div><div class="detail-row"><span>Bắt đầu</span><span>'+esc(new Date(c2.START_AT).toLocaleString('vi-VN'))+'</span></div></div>'+inputHtml('Giờ máy cuối','main-endmeter','number','')+'<button class="btn-big primary" id="main-end"><span class="icon">⏹</span><span>KẾT THÚC</span></button>'}
        else{html='<div class="account-card">'+selectHtml('Xe công trình','main-machine',h.machines||[],function(x){return (x.name||x.code)+(x.code?' - '+x.code:'')})+selectHtml('Công việc','main-work',h.workTypes||[],function(x){return x.name})+inputHtml('Giờ máy đầu','main-startmeter','number','')+'</div><button class="btn-big primary" id="main-start"><span class="icon">▶</span><span>BẮT ĐẦU</span></button>'}
      }
      s.innerHTML=shell(u.FULL_NAME,u.ROLE==='DRIVER'?'Tài xế xe tải':'Lái xe công trình',html);
      var start=s.querySelector('#main-start');if(start)start.onclick=async function(){try{start.disabled=true;if(u.ROLE==='DRIVER'){var v=s.querySelector('#main-vehicle').value,r=s.querySelector('#main-route').value;if(!v||!r){toast('Vui lòng chọn xe tải và tuyến.','error');start.disabled=false;return}var g=await gps();await tx('trip/start',{vehicleId:v,routeId:r,lat:g?.latitude,lng:g?.longitude})}else{var m=s.querySelector('#main-machine').value,w=s.querySelector('#main-work').value;if(!m||!w){toast('Vui lòng chọn xe công trình và công việc.','error');start.disabled=false;return}var g2=await gps();await tx('shift/start',{machineId:m,workTypeId:w,startHourMeter:Number(s.querySelector('#main-startmeter').value||0)||null,lat:g2?.latitude,lng:g2?.longitude})}toast('Đã bắt đầu.','success');setTimeout(renderHome,150)}catch(e){toast(e.message||'Không thể bắt đầu.','error');start.disabled=false}};
      var finish=s.querySelector('#main-finish');if(finish)finish.onclick=async function(){try{finish.disabled=true;var g3=await gps();await tx('trip/complete',{lat:g3?.latitude,lng:g3?.longitude});toast('Đã kết thúc chuyến.','success');setTimeout(renderHome,150)}catch(e){toast(e.message||'Không thể kết thúc chuyến.','error');finish.disabled=false}};
      var end=s.querySelector('#main-end');if(end)end.onclick=async function(){try{end.disabled=true;var g4=await gps();await tx('shift/end',{endHourMeter:Number(s.querySelector('#main-endmeter').value||0)||null,lat:g4?.latitude,lng:g4?.longitude});localStorage.removeItem('local_active_machine');toast('Đã kết thúc.','success');setTimeout(renderHome,150)}catch(e){toast(e.message||'Không thể kết thúc.','error');end.disabled=false}};
    }catch(e){s.innerHTML=shell(u.FULL_NAME,'','<div class="form-error show">'+esc(e.message||'Không tải được dữ liệu.')+'</div>')}
    busy=false;return true
  }

  function inlinePage(title,body){return '<div class="screen"><div class="page-header" style="padding:18px 18px 4px"><h2>'+esc(title)+'</h2></div><div class="page-body">'+body+'</div></div>'}
  async function renderOperations(){
    var u=user();if(!u||!['DRIVER','OPERATOR'].includes(u.ROLE))return false;ensureNav();active('operations-v2');var s=document.getElementById('screen');var body='<p style="color:var(--color-text-muted);margin:0 0 16px">Các nghiệp vụ phát sinh trong quá trình vận hành.</p><div class="action-list" style="padding:0"><button class="btn-big" id="op-fuel"><span class="icon">⛽</span><span>ĐỔ DẦU</span></button><button class="btn-big" id="op-issue"><span class="icon">🔧</span><span>GHI NHẬN SỰ CỐ</span></button><div id="op-stop-wrap"></div></div>';s.innerHTML=inlinePage('Vận hành',body);
    s.querySelector('#op-fuel').onclick=renderFuel;s.querySelector('#op-issue').onclick=renderIssue;
    if(u.ROLE==='DRIVER'){try{var h=await Api.get('home',{});if(h.currentTrip){s.querySelector('#op-stop-wrap').innerHTML='<button class="btn-big danger-outline" id="op-stop"><span class="icon">⛔</span><span>DỪNG XE DO SỰ CỐ</span></button>';s.querySelector('#op-stop').onclick=renderStop}}catch(e){}}
    return true
  }
  function renderFuel(){var s=document.getElementById('screen');active('operations-v2');s.innerHTML=inlinePage('Đổ dầu',inputHtml('Số lít *','fuel-qty','number','')+inputHtml('Công tơ mét / giờ máy','fuel-meter','number','')+inputHtml('Ghi chú','fuel-note','text','')+'<button class="btn-primary" id="fuel-save">GHI NHẬN ĐỔ DẦU</button>');s.querySelector('#fuel-save').onclick=async function(){var q=Number(s.querySelector('#fuel-qty').value||0);if(q<=0){toast('Số lít phải lớn hơn 0.','error');return}try{await tx('fuel',{quantity:q,hourMeter:Number(s.querySelector('#fuel-meter').value||0)||null,note:s.querySelector('#fuel-note').value});toast('Đã ghi nhận đổ dầu.','success');renderOperations()}catch(e){toast(e.message||'Không thể ghi nhận đổ dầu.','error')}}}
  function renderIssue(){var s=document.getElementById('screen');active('operations-v2');s.innerHTML=inlinePage('Ghi nhận sự cố',inputHtml('Loại sự cố','issue-type','text','Động cơ, thủy lực, lốp...')+inputHtml('Mô tả *','issue-desc','text','')+'<div class="field"><label>Mức độ</label><select class="select-field" id="issue-sev"><option value="LOW">Vẫn hoạt động</option><option value="MEDIUM">Hoạt động hạn chế</option><option value="HIGH">Phải dừng xe/máy</option></select></div><button class="btn-primary" id="issue-save">GHI NHẬN</button>');s.querySelector('#issue-save').onclick=async function(){var d=s.querySelector('#issue-desc').value.trim();if(!d){toast('Vui lòng nhập mô tả.','error');return}try{await tx('issue',{issueType:s.querySelector('#issue-type').value,severity:s.querySelector('#issue-sev').value,description:d});toast('Đã ghi nhận sự cố.','success');renderOperations()}catch(e){toast(e.message||'Không thể ghi nhận sự cố.','error')}}}
  async function renderStop(){var s=document.getElementById('screen');active('operations-v2');s.innerHTML=inlinePage('Dừng xe do sự cố','<p style="color:var(--color-text-muted);margin-top:0">Dùng khi xe đang chạy và phải dừng do sự cố.</p>'+inputHtml('Loại sự cố','stop-type','text','Lốp, động cơ, phanh...')+inputHtml('Mô tả *','stop-desc','text','')+'<button class="btn-primary" id="stop-save" style="background:#dc2626">DỪNG XE VÀ GHI NHẬN</button>');s.querySelector('#stop-save').onclick=async function(){var d=s.querySelector('#stop-desc').value.trim();if(!d){toast('Vui lòng nhập mô tả.','error');return}try{var g=await gps();await tx('trip/pause',{reason:'INCIDENT',note:d,lat:g?.latitude,lng:g?.longitude});await tx('issue',{issueType:s.querySelector('#stop-type').value,severity:'HIGH',description:d,lat:g?.latitude,lng:g?.longitude});toast('Đã dừng xe và ghi nhận sự cố.','success');renderOperations()}catch(e){toast(e.message||'Không thể dừng xe.','error')}}}

  async function renderAccount(){
    var u=user();if(!u||!['DRIVER','OPERATOR'].includes(u.ROLE))return false;ensureNav();active('account');var s=document.getElementById('screen'),role=u.ROLE==='DRIVER'?'Tài xế xe tải':'Lái xe công trình';s.innerHTML='<div class="screen"><div class="app-header"><p class="greeting">Tài khoản</p><p class="user-name">'+esc(u.FULL_NAME)+'</p></div><div class="account-card"><p class="name">'+esc(u.FULL_NAME)+'</p><span class="role-badge">'+role+'</span><div class="detail-row"><span>Số điện thoại</span><span>'+esc(u.PHONE||'')+'</span></div><div class="detail-row"><span>Trạng thái</span><span>Đang hoạt động</span></div></div><button class="btn-big" id="change-vehicle"><span class="icon">🔄</span><span>ĐỔI XE</span></button><button class="btn-logout" id="logout-v15">ĐĂNG XUẤT</button></div>';
    s.querySelector('#change-vehicle').onclick=async function(){try{var h=await Api.get('home',{});if(u.ROLE==='DRIVER'&&h.currentTrip){toast('Hãy kết thúc chuyến hiện tại trước khi đổi xe.','warning');return}if(u.ROLE==='OPERATOR'&&h.currentShift){toast('Hãy kết thúc ca hiện tại trước khi đổi xe.','warning');return}localStorage.removeItem('local_active_machine');renderHome()}catch(e){toast(e.message||'Không thể đổi xe.','error')}};
    s.querySelector('#logout-v15').onclick=async function(){await Api.logout();localStorage.removeItem('local_active_machine');location.reload()};return true
  }

  function intercept(e){var b=e.target.closest&&e.target.closest('#bottom-nav button');if(!b)return;var u=user();if(!u||!['DRIVER','OPERATOR'].includes(u.ROLE))return;var r=b.dataset.route;if(!['home','operations-v2','account'].includes(r))return;e.preventDefault();e.stopImmediatePropagation();if(r==='home')renderHome();else if(r==='operations-v2')renderOperations();else renderAccount()}
  document.addEventListener('click',intercept,true);
  function enforce(){if(busy)return;var u=user();if(!u||!['DRIVER','OPERATOR'].includes(u.ROLE))return;var nav=document.getElementById('bottom-nav');if(!nav||nav.classList.contains('hidden'))return;var a=nav.querySelector('button.active');if(!a)return;var s=document.getElementById('screen');if(a.dataset.route==='home'&&!s.querySelector('#main-start')&&!s.querySelector('#main-finish')&&!s.querySelector('#main-end'))renderHome()}
  document.addEventListener('DOMContentLoaded',function(){new MutationObserver(function(){setTimeout(enforce,10)}).observe(document.getElementById('screen'),{childList:true,subtree:true});setTimeout(enforce,300)});
  window.NSV15={home:renderHome,operations:renderOperations,account:renderAccount};
})();