(function(){
  var rendering=false;
  function u(){return window.Api&&Api.getCurrentUser?Api.getCurrentUser():null}
  function esc(s){var d=document.createElement('div');d.textContent=s==null?'':String(s);return d.innerHTML}
  function toast(msg,type){var c=document.getElementById('toast-container');if(!c)return;var x=document.createElement('div');x.className='toast '+(type||'')+' show';x.textContent=msg;c.appendChild(x);setTimeout(function(){x.remove()},2800)}
  function active(route){document.querySelectorAll('#bottom-nav button').forEach(function(b){b.classList.toggle('active',b.dataset.route===route)})}
  function closeOverlays(){document.getElementById('role-v2-panel')?.remove();document.getElementById('admin-panel')?.remove()}
  async function gps(){try{return await Gps.getCurrentPosition()}catch(e){return null}}
  async function tx(action,payload){payload=payload||{};payload.clientTransactionId=payload.clientTransactionId||crypto.randomUUID();if(navigator.onLine){try{return await Api.post(action,payload)}catch(e){if(e&&e.code&&e.code!=='PARSE_ERROR')throw e}}await OfflineQueue.enqueue(action,payload);toast('Đã lưu tạm, sẽ đồng bộ khi có mạng.','warning');return {offline:true}}
  function selectHtml(label,id,items,fmt){return '<div class="field"><label>'+label+'</label><select class="select-field" id="'+id+'"><option value="">-- Chọn --</option>'+items.map(function(x){return '<option value="'+x.id+'">'+esc(fmt(x))+'</option>'}).join('')+'</select></div>'}
  function inputHtml(label,id,type,ph){return '<div class="field"><label>'+label+'</label><input id="'+id+'" type="'+(type||'text')+'" '+(type==='number'?'inputmode="decimal" step="0.1"':'')+' placeholder="'+esc(ph||'')+'"></div>'}
  function shell(title,subtitle,body){return '<div class="screen"><div class="app-header"><p class="greeting">'+esc(subtitle||'')+'</p><p class="user-name">'+esc(title)+'</p></div><div class="action-list" style="padding-top:18px">'+body+'</div></div>'}
  async function renderHome(){
    var user=u();if(!user||!['DRIVER','OPERATOR'].includes(user.ROLE))return false;
    closeOverlays();active('home');rendering=true;var s=document.getElementById('screen');s.dataset.roleV2=user.ROLE;s.innerHTML=shell(user.FULL_NAME,user.ROLE==='DRIVER'?'Tài xế xe tải':'Lái xe công trình','<div class="loading-wrap"><div class="spinner"></div> Đang tải...</div>');
    try{
      var h=await Api.get('home',{}),html='';
      if(user.ROLE==='DRIVER'){
        if(h.currentTrip){var c=h.currentTrip;html='<div class="account-card"><p class="name">🚚 '+esc(c.PLATE_NUMBER||c.VEHICLE_ID)+'</p><div class="detail-row"><span>Tuyến</span><span>'+esc(c.ROUTE_NAME||'—')+'</span></div><div class="detail-row"><span>Hành trình</span><span>'+esc((c.ORIGIN||'')+' → '+(c.DESTINATION||''))+'</span></div><div class="detail-row"><span>Trạng thái</span><span>Đang chạy</span></div></div><button class="btn-big primary" id="main-finish"><span class="icon">⏹</span><span>KẾT THÚC CHUYẾN</span></button>';
        }else{html='<div class="account-card">'+selectHtml('Xe tải / Chuyến','main-vehicle',h.vehicles||[],function(x){return (x.plate_number||x.code)+' - '+(x.name||'')})+selectHtml('Tuyến','main-route',h.routes||[],function(x){return x.name+' · '+x.origin+' → '+x.destination})+'</div><button class="btn-big primary" id="main-start"><span class="icon">▶</span><span>BẮT ĐẦU CHUYẾN</span></button>'}
      }else{
        if(h.currentShift){var c2=h.currentShift;html='<div class="account-card"><p class="name">🚜 '+esc(c2.MACHINE_NAME||c2.MACHINE_ID)+'</p><div class="detail-row"><span>Công việc</span><span>'+esc(c2.WORK_TYPE_NAME||'—')+'</span></div><div class="detail-row"><span>Bắt đầu</span><span>'+esc(new Date(c2.START_AT).toLocaleString('vi-VN'))+'</span></div></div>'+inputHtml('Giờ máy cuối','main-endmeter','number','')+'<button class="btn-big primary" id="main-end"><span class="icon">⏹</span><span>KẾT THÚC</span></button>';
        }else{html='<div class="account-card">'+selectHtml('Xe công trình','main-machine',h.machines||[],function(x){return (x.name||x.code)+' - '+x.code})+selectHtml('Công việc','main-work',h.workTypes||[],function(x){return x.name})+inputHtml('Giờ máy đầu','main-startmeter','number','')+'</div><button class="btn-big primary" id="main-start"><span class="icon">▶</span><span>BẮT ĐẦU</span></button>'}
      }
      s.innerHTML=shell(user.FULL_NAME,user.ROLE==='DRIVER'?'Tài xế xe tải':'Lái xe công trình',html);
      var b=s.querySelector('#main-start');if(b)b.onclick=async function(){try{b.disabled=true;if(user.ROLE==='DRIVER'){var v=s.querySelector('#main-vehicle').value,r=s.querySelector('#main-route').value;if(!v||!r){toast('Vui lòng chọn xe tải và tuyến.','error');b.disabled=false;return}var g=await gps();await tx('trip/start',{vehicleId:v,routeId:r,lat:g?.latitude,lng:g?.longitude})}else{var m=s.querySelector('#main-machine').value,w=s.querySelector('#main-work').value;if(!m||!w){toast('Vui lòng chọn xe công trình và công việc.','error');b.disabled=false;return}var g2=await gps();await tx('shift/start',{machineId:m,workTypeId:w,startHourMeter:Number(s.querySelector('#main-startmeter').value||0)||null,lat:g2?.latitude,lng:g2?.longitude})}toast('Đã bắt đầu.','success');setTimeout(renderHome,200)}catch(e){toast(e.message||'Không thể bắt đầu.','error');b.disabled=false}};
      var f=s.querySelector('#main-finish');if(f)f.onclick=async function(){try{f.disabled=true;var g=await gps();await tx('trip/complete',{lat:g?.latitude,lng:g?.longitude});toast('Đã kết thúc chuyến.','success');setTimeout(renderHome,200)}catch(e){toast(e.message||'Không thể kết thúc chuyến.','error');f.disabled=false}};
      var ebtn=s.querySelector('#main-end');if(ebtn)ebtn.onclick=async function(){try{ebtn.disabled=true;var g=await gps();await tx('shift/end',{endHourMeter:Number(s.querySelector('#main-endmeter').value||0)||null,lat:g?.latitude,lng:g?.longitude});localStorage.removeItem('local_active_machine');toast('Đã kết thúc.','success');setTimeout(renderHome,200)}catch(e){toast(e.message||'Không thể kết thúc.','error');ebtn.disabled=false}};
    }catch(e){s.innerHTML=shell(user.FULL_NAME,'','<div class="form-error show">'+esc(e.message||'Không tải được dữ liệu.')+'</div>')}
    rendering=false;return true
  }
  async function renderOperations(){
    var user=u();if(!user||!['DRIVER','OPERATOR'].includes(user.ROLE))return false;closeOverlays();active('operations-v2');var s=document.getElementById('screen');s.innerHTML='<div class="screen"><div class="page-header" style="padding:18px 18px 4px"><h2>Vận hành</h2></div><div class="page-body"><p style="color:var(--color-text-muted);margin:0 0 16px">Các nghiệp vụ phát sinh trong quá trình vận hành.</p><div class="action-list" style="padding:0"><button class="btn-big" id="op-fuel"><span class="icon">⛽</span><span>ĐỔ DẦU</span></button><button class="btn-big" id="op-issue"><span class="icon">🔧</span><span>GHI NHẬN SỰ CỐ</span></button><div id="op-stop-wrap"></div></div></div></div>';
    s.querySelector('#op-fuel').onclick=function(){NSRoleV2&&NSRoleV2.openFuel&&NSRoleV2.openFuel()};s.querySelector('#op-issue').onclick=function(){NSRoleV2&&NSRoleV2.openIssue&&NSRoleV2.openIssue()};
    if(user.ROLE==='DRIVER'){try{var h=await Api.get('home',{});if(h.currentTrip){s.querySelector('#op-stop-wrap').innerHTML='<button class="btn-big danger-outline" id="op-stop"><span class="icon">⛔</span><span>DỪNG XE DO SỰ CỐ</span></button>';s.querySelector('#op-stop').onclick=function(){NSRoleV2&&NSRoleV2.openStopIncident&&NSRoleV2.openStopIncident()}}}catch(e){}}
    return true
  }
  async function renderAccount(){
    var user=u();if(!user||!['DRIVER','OPERATOR'].includes(user.ROLE))return false;closeOverlays();active('account');var s=document.getElementById('screen'),role=user.ROLE==='DRIVER'?'Tài xế xe tải':'Lái xe công trình';s.innerHTML='<div class="screen"><div class="app-header"><p class="greeting">Tài khoản</p><p class="user-name">'+esc(user.FULL_NAME)+'</p></div><div class="account-card"><p class="name">'+esc(user.FULL_NAME)+'</p><span class="role-badge">'+role+'</span><div class="detail-row"><span>Số điện thoại</span><span>'+esc(user.PHONE||'')+'</span></div><div class="detail-row"><span>Trạng thái</span><span>Đang hoạt động</span></div></div><button class="btn-big" id="change-vehicle-btn"><span class="icon">🔄</span><span>ĐỔI XE</span></button><button class="btn-logout" id="custom-logout">ĐĂNG XUẤT</button></div>';
    s.querySelector('#change-vehicle-btn').onclick=async function(){try{var h=await Api.get('home',{});if(user.ROLE==='DRIVER'&&h.currentTrip){toast('Hãy kết thúc chuyến hiện tại trước khi đổi xe.','warning');return}if(user.ROLE==='OPERATOR'&&h.currentShift){toast('Hãy kết thúc ca hiện tại trước khi đổi xe.','warning');return}localStorage.removeItem('local_active_machine');await renderHome()}catch(e){toast(e.message||'Không thể đổi xe.','error')}};
    s.querySelector('#custom-logout').onclick=async function(){await Api.logout();localStorage.removeItem('local_active_machine');location.reload()};return true
  }
  function intercept(e){var b=e.target.closest&&e.target.closest('#bottom-nav button');if(!b)return;var user=u();if(!user||!['DRIVER','OPERATOR'].includes(user.ROLE))return;var r=b.dataset.route;if(!['home','operations-v2','account'].includes(r))return;e.preventDefault();e.stopImmediatePropagation();if(r==='home')renderHome();else if(r==='operations-v2')renderOperations();else renderAccount()}
  document.addEventListener('click',intercept,true);
  function enforce(){if(rendering)return;var user=u();if(!user||!['DRIVER','OPERATOR'].includes(user.ROLE))return;var nav=document.getElementById('bottom-nav');if(!nav||nav.classList.contains('hidden'))return;var activeBtn=nav.querySelector('button.active');var route=activeBtn&&activeBtn.dataset.route;if(document.getElementById('role-v2-panel'))document.getElementById('role-v2-panel').remove();var s=document.getElementById('screen');if(route==='home'&&s&&!s.querySelector('#main-start')&&!s.querySelector('#main-finish')&&!s.querySelector('#main-end'))renderHome();}
  document.addEventListener('DOMContentLoaded',function(){new MutationObserver(function(){setTimeout(enforce,20)}).observe(document.body,{childList:true,subtree:true});setTimeout(enforce,500)});
  window.NSFinalUI={home:renderHome,operations:renderOperations,account:renderAccount};
})();