// V1 polish: giữ phương tiện + tuyến/công việc trên Trang chủ, hỗ trợ offline, làm nổi bật thao tác chính.
(function(){
'use strict';
if(window.__NS_V1_POLISH)return;window.__NS_V1_POLISH=true;
const ACCOUNT_API='https://dnqhikwqihfxvezqzqzn.supabase.co/functions/v1/nghi-son-account-api';
let scheduled=false,warming=false;
function u(){try{return typeof Api!=='undefined'&&Api.getCurrentUser?Api.getCurrentUser():null}catch(e){return null}}
function key(n){return 'ns_v1_'+n+'_'+(u()?.PROFILE_ID||'user')}
function toast(m,t){const c=document.getElementById('toast-container');if(!c)return;const x=document.createElement('div');x.className='toast '+(t||'')+' show';x.textContent=m;c.appendChild(x);setTimeout(()=>x.remove(),2800)}
function jget(k,d=null){try{return JSON.parse(localStorage.getItem(k)||'null')||d}catch(e){return d}}
function jset(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
async function gpsNow(){try{return typeof Gps!=='undefined'&&Gps.getCurrentPosition?await Gps.getCurrentPosition(6500):null}catch(e){return null}}
async function cachedAccount(){const k=key('account');if(navigator.onLine){try{const q=new URLSearchParams({action:'account',token:localStorage.getItem('auth_token')||''});const r=await fetch(ACCOUNT_API+'?'+q);const j=await r.json();if(j.success){jset(k,j.data);return j.data}}catch(e){}}return jget(k,{})}
async function warm(){if(warming||!navigator.onLine||typeof Api==='undefined')return;const user=u();if(!user)return;warming=true;try{await cachedAccount();const h=await Api.get('home',{});jset(key('home'),h)}catch(e){}finally{warming=false}}
async function tx(action,payload){payload=payload||{};payload.clientTransactionId=payload.clientTransactionId||crypto.randomUUID();if(navigator.onLine){try{return await Api.post(action,payload)}catch(e){const c=e&&e.code||'';if(c&&c!=='NETWORK_ERROR'&&c!=='PARSE_ERROR')throw e}}if(typeof OfflineQueue==='undefined')throw new Error('Không khởi tạo được bộ nhớ offline.');await OfflineQueue.enqueue(action,payload);toast('Đã ghi nhận trên máy · chờ đồng bộ','warning');return {offline:true}}
function css(){if(document.getElementById('ns-v1-polish-css'))return;const s=document.createElement('style');s.id='ns-v1-polish-css';s.textContent=`
.v17-action.start,#start-trip,#start-shift{background:#159447!important;color:#fff!important;border:2px solid #159447!important;box-shadow:0 8px 18px rgba(21,148,71,.22)!important;justify-content:center!important;min-height:60px!important}.v17-action.stop,#finish-trip,#finish-shift{background:#d9473f!important;color:#fff!important;border:2px solid #d9473f!important;box-shadow:0 8px 18px rgba(217,71,63,.2)!important;justify-content:center!important;min-height:60px!important}.v17-action.start span,.v17-action.stop span{color:inherit!important}
.ns-home-asset{background:#eef8f7;border:1px solid #cce9e6;border-radius:13px;padding:11px 13px;margin:0 0 12px;display:flex;justify-content:space-between;gap:12px;align-items:center}.ns-home-asset span{font-size:13px;color:#667085}.ns-home-asset b{font-size:17px;color:#075f61}
.ns-active-select{margin-top:10px}.ns-active-select label{display:block;font-size:13px;font-weight:800;color:#334155;margin-bottom:7px}.ns-active-select select{width:100%;min-height:48px;border:1.5px solid #cbd8df;border-radius:13px;background:#fff;padding:11px 12px;font-size:16px}
.ns-ops-menu{display:grid!important;gap:12px!important;background:transparent!important;border:0!important;padding:0!important;box-shadow:none!important}.ns-ops-menu button{min-height:76px!important;border:1.5px solid #d6e6e4!important;border-radius:18px!important;padding:0 16px!important;background:#fff!important;font-size:17px!important;box-shadow:0 5px 15px rgba(15,23,42,.05)!important}.ns-ops-menu button#all-fuel{background:#eef9f7!important;border-color:#bfe3de!important;color:#075f61!important}.ns-ops-menu button#all-issue{background:#fff7ed!important;border-color:#fed7aa!important;color:#9a4c0d!important}.ns-ops-menu .ico{width:42px!important;height:42px!important;border-radius:13px;background:rgba(255,255,255,.75)!important}
#fuel-save-all,#issue-save-all{width:100%!important;min-height:60px!important;border-radius:16px!important;justify-content:center!important;font-size:16px!important;font-weight:850!important;box-shadow:0 8px 18px rgba(8,113,115,.18)!important}#fuel-save-all:not(:disabled){background:#087173!important;color:#fff!important;border:2px solid #087173!important}#issue-save-all:not(:disabled){background:#c85a16!important;color:#fff!important;border:2px solid #c85a16!important}#fuel-save-all:disabled,#issue-save-all:disabled{background:#e7ebee!important;color:#8b95a1!important;border:2px solid #e7ebee!important;box-shadow:none!important;opacity:1!important}
#fuel-q,#fuel-meter,#issue-desc-all{min-height:52px!important}.v17-card:has(#fuel-q){border-top:4px solid #087173!important}.v17-card:has(#issue-desc-all){border-top:4px solid #c85a16!important}.ux-chip{min-height:52px!important}.ns-photo-action{min-height:58px!important}
`;document.head.appendChild(s)}
function assetLabel(acc){const a=acc?.selectedAsset;return a?(a.plate_number||a.name||a.code||'Đã chọn'):'Chưa chọn phương tiện'}
function ensureAssetRow(card,label){if(!card||card.querySelector('.ns-home-asset'))return;const d=document.createElement('div');d.className='ns-home-asset';d.innerHTML='<span>Phương tiện đang sử dụng</span><b></b>';d.querySelector('b').textContent=label;const title=card.querySelector('.v17-card-title');if(title)title.after(d);else card.prepend(d)}
function opts(items,selected,kind){return '<option value="">-- Chọn '+kind+' --</option>'+items.map(x=>`<option value="${x.id}" ${x.id===selected?'selected':''}>${kind==='tuyến'?((x.origin||'')+' → '+(x.destination||'')):(x.name||'')}</option>`).join('')}
function replace(id,fn){const o=document.getElementById(id);if(!o||o.dataset.nsPolish)return o;const b=o.cloneNode(true);b.dataset.nsPolish='1';o.replaceWith(b);b.addEventListener('click',fn);return b}
async function driver(){const user=u();if(user?.ROLE!=='DRIVER')return;const acc=await cachedAccount(),label=assetLabel(acc);const start=document.getElementById('start-trip'),finish=document.getElementById('finish-trip');let route=document.getElementById('route-select')||document.getElementById('v1-route-active');const home=jget(key('home'),{}),routes=home.routes||[];const saved=localStorage.getItem(key('route'))||'';
if(start){const card=start.closest('.v17-wrap')?.querySelector('.v17-card');ensureAssetRow(card,label);const title=card?.querySelector('.v17-card-title');if(title)title.textContent='CHUYẾN MỚI';if(route){route.closest('.v17-field')?.style.removeProperty('display');const lab=route.closest('.v17-field')?.querySelector('label');if(lab)lab.textContent='Tuyến / hành trình';if(saved&&[...route.options].some(o=>o.value===saved))route.value=saved;route.onchange=()=>localStorage.setItem(key('route'),route.value)}replace('start-trip',async e=>{const b=e.currentTarget;if(b.disabled)return;const a=(await cachedAccount())?.selectedAsset;if(!a)return toast('Vui lòng chọn xe trước.','error');const rid=(document.getElementById('route-select')?.value||localStorage.getItem(key('route'))||'');if(rid)localStorage.setItem(key('route'),rid);try{b.disabled=true;const g=await gpsNow();const r=await tx('trip/start',{vehicleId:a.id,routeId:rid||null,lat:g?.latitude??null,lng:g?.longitude??null});if(r.offline){jset(key('local_trip'),{active:true,vehicleId:a.id,routeId:rid,startedAt:new Date().toISOString()});toast('Đã bắt đầu chuyến trên máy · chờ đồng bộ','success');localTripView(label,routes,rid)}else{localStorage.removeItem(key('local_trip'));toast('Đã bắt đầu chuyến.','success');window.navigate?.('home')}}catch(err){toast(err.message||err,'error');b.disabled=false}})}
if(finish){const card=finish.closest('.v17-wrap')?.querySelector('.v17-card');ensureAssetRow(card,label);const title=card?.querySelector('.v17-card-title');if(title)title.textContent='CHUYẾN ĐANG CHẠY';if(!document.getElementById('v1-route-active')){const d=document.createElement('div');d.className='ns-active-select';d.innerHTML='<label>Tuyến / hành trình</label><select id="v1-route-active">'+opts(routes,saved,'tuyến')+'</select>';card?.appendChild(d);route=d.querySelector('select');route.onchange=()=>localStorage.setItem(key('route'),route.value)}replace('finish-trip',async e=>{const b=e.currentTarget;const rid=document.getElementById('v1-route-active')?.value||localStorage.getItem(key('route'))||'';try{b.disabled=true;const g=await gpsNow();const r=await tx('trip/complete',{routeId:rid||null,lat:g?.latitude??null,lng:g?.longitude??null});if(r.offline){localStorage.removeItem(key('local_trip'));toast('Đã kết thúc chuyến trên máy · chờ đồng bộ','success');b.textContent='ĐÃ GHI NHẬN KẾT THÚC';b.disabled=true}else{toast('Đã kết thúc chuyến.','success');window.navigate?.('home')}}catch(err){toast(err.message||err,'error');b.disabled=false}})}
const lt=jget(key('local_trip'));if(lt?.active&&!finish&&start)localTripView(label,routes,lt.routeId||saved)}
function localTripView(label,routes,rid){const wrap=document.querySelector('#screen .v17-wrap');if(!wrap)return;wrap.innerHTML=`<div class="v17-card"><div class="v17-card-title">CHUYẾN ĐANG CHẠY · CHƯA ĐỒNG BỘ</div><div class="ns-home-asset"><span>Phương tiện đang sử dụng</span><b>${label}</b></div><div class="ns-active-select"><label>Tuyến / hành trình</label><select id="v1-route-active">${opts(routes,rid,'tuyến')}</select></div></div><button id="finish-trip" class="v17-action stop"><b>KẾT THÚC CHUYẾN</b></button>`;document.getElementById('v1-route-active').onchange=e=>localStorage.setItem(key('route'),e.target.value);schedule()}
async function operator(){const user=u();if(user?.ROLE!=='OPERATOR')return;const acc=await cachedAccount(),label=assetLabel(acc),home=jget(key('home'),{}),works=home.workTypes||[];const start=document.getElementById('start-shift'),finish=document.getElementById('finish-shift');let work=document.getElementById('work-select')||document.getElementById('v1-work-active');const saved=localStorage.getItem(key('work'))||'';
if(start){const card=start.closest('.v17-wrap')?.querySelector('.v17-card');ensureAssetRow(card,label);if(work){if(saved&&[...work.options].some(o=>o.value===saved))work.value=saved;work.onchange=()=>localStorage.setItem(key('work'),work.value)}replace('start-shift',async e=>{const b=e.currentTarget,w=document.getElementById('work-select')?.value||'',meter=Number(document.getElementById('start-meter')?.value||0);if(!w)return toast('Vui lòng chọn công việc.','error');if(!(meter>0))return toast('Giờ máy đầu phải lớn hơn 0.','error');const a=(await cachedAccount())?.selectedAsset;if(!a)return toast('Vui lòng chọn máy trước.','error');localStorage.setItem(key('work'),w);try{b.disabled=true;const g=await gpsNow();const r=await tx('shift/start',{machineId:a.id,workTypeId:w,startHourMeter:meter,lat:g?.latitude??null,lng:g?.longitude??null});localStorage.setItem(key('shift_start'),String(meter));if(r.offline){jset(key('local_shift'),{active:true,machineId:a.id,workTypeId:w,startMeter:meter});toast('Đã bắt đầu ca trên máy · chờ đồng bộ','success');localShiftView(label,works,w,meter)}else{localStorage.removeItem(key('local_shift'));toast('Đã bắt đầu ca.','success');window.navigate?.('home')}}catch(err){toast(err.message||err,'error');b.disabled=false}})}
if(finish){const card=finish.closest('.v17-wrap')?.querySelector('.v17-card');ensureAssetRow(card,label);if(!document.getElementById('v1-work-active')){const d=document.createElement('div');d.className='ns-active-select';d.innerHTML='<label>Công việc thực tế</label><select id="v1-work-active">'+opts(works,saved,'công việc')+'</select>';card?.appendChild(d);work=d.querySelector('select');work.onchange=()=>localStorage.setItem(key('work'),work.value)}replace('finish-shift',async e=>{const b=e.currentTarget,meter=Number(document.getElementById('end-meter')?.value||0),sm=Number(localStorage.getItem(key('shift_start'))||0),wid=document.getElementById('v1-work-active')?.value||localStorage.getItem(key('work'))||'';if(!(meter>0))return toast('Giờ máy cuối phải lớn hơn 0.','error');if(sm&&meter<sm)return toast('Giờ máy cuối không được nhỏ hơn giờ máy đầu.','error');try{b.disabled=true;const g=await gpsNow();const r=await tx('shift/end',{endHourMeter:meter,workTypeId:wid||null,lat:g?.latitude??null,lng:g?.longitude??null});if(r.offline){localStorage.removeItem(key('local_shift'));toast('Đã kết thúc ca trên máy · chờ đồng bộ','success');b.textContent='ĐÃ GHI NHẬN KẾT THÚC';b.disabled=true}else{toast('Đã kết thúc ca.','success');window.navigate?.('home')}}catch(err){toast(err.message||err,'error');b.disabled=false}})}
const ls=jget(key('local_shift'));if(ls?.active&&!finish&&start)localShiftView(label,works,ls.workTypeId||saved,ls.startMeter)}
function localShiftView(label,works,wid,startMeter){const wrap=document.querySelector('#screen .v17-wrap');if(!wrap)return;wrap.innerHTML=`<div class="v17-card"><div class="v17-card-title">CA ĐANG HOẠT ĐỘNG · CHƯA ĐỒNG BỘ</div><div class="ns-home-asset"><span>Phương tiện đang sử dụng</span><b>${label}</b></div><div class="v17-row"><span>Giờ máy đầu</span><span>${startMeter||'—'}</span></div><div class="ns-active-select"><label>Công việc thực tế</label><select id="v1-work-active">${opts(works,wid,'công việc')}</select></div><div class="v17-field" style="margin-top:12px"><label>Giờ máy cuối *</label><input id="end-meter" type="number" inputmode="decimal" step="0.1"></div></div><button id="finish-shift" class="v17-action stop"><b>KẾT THÚC</b></button>`;document.getElementById('v1-work-active').onchange=e=>localStorage.setItem(key('work'),e.target.value);schedule()}
function ops(){const menu=document.querySelector('.ns-ops-menu');if(menu)menu.dataset.polished='1';const fq=document.getElementById('fuel-q'),fm=document.getElementById('fuel-meter'),fs=document.getElementById('fuel-save-all');if(fq&&fm&&fs&&!fs.dataset.validated){fs.dataset.validated='1';const check=()=>{const asset=document.getElementById('op-asset');fs.disabled=!(Number(fq.value)>0&&Number(fm.value)>0&&(!asset||!!asset.value))};['input','change'].forEach(ev=>document.getElementById('screen').addEventListener(ev,check));check()}
const id=document.getElementById('issue-desc-all'),it=document.getElementById('issue-type-all'),is=document.getElementById('issue-save-all');if(id&&is&&!is.dataset.validated){is.dataset.validated='1';const check=()=>{const asset=document.getElementById('op-asset');is.disabled=!(id.value.trim()&&(!it||String(it.value||'').trim())&&(!asset||!!asset.value))};['input','change'].forEach(ev=>document.getElementById('screen').addEventListener(ev,check));check()}}
function apply(){css();warm();driver();operator();ops()}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;apply()})}
function boot(){apply();const root=document.getElementById('screen');if(root)new MutationObserver(m=>{if(m.some(x=>x.addedNodes?.length))schedule()}).observe(root,{childList:true,subtree:true});window.addEventListener('online',()=>{warm();setTimeout(()=>window.navigate?.('home'),500)});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
